# Generated by Django 5.2.11 on 2026-02-25 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0013_recentsearch_delete_propertyoffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Offer title displayed to users', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed offer description')),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('flat', 'Flat Amount Discount'), ('bogo', 'Buy One Get One'), ('bundle', 'Bundle Offer')], max_length=20)),
                ('coupon_code', models.CharField(help_text='Coupon code for applying offer', max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount (0-100)', max_digits=5)),
                ('discount_flat', models.DecimalField(decimal_places=2, default=0, help_text='Flat amount discount', max_digits=10)),
                ('start_datetime', models.DateTimeField(help_text='When offer becomes active')),
                ('end_datetime', models.DateTimeField(help_text='When offer expires')),
                ('is_active', models.BooleanField(default=True)),
                ('is_global', models.BooleanField(default=False, help_text='True = applies to all properties. False = specific properties only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicable_properties', to='offers.offer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='hotels.property')),
            ],
            options={
                'verbose_name': 'Property Offer',
                'verbose_name_plural': 'Property Offers',
                'unique_together': {('offer', 'property')},
            },
        ),
    ]
