# Generated by Django 5.1.5 on 2026-03-11 09:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='For anonymous carts before login', max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bundle_ref', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('title', models.CharField(blank=True, help_text="e.g. 'Goa Trip Dec 2025'", max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('partially_confirmed', 'Partially Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('destination_city', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('bundle_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Extra discount for multi-product bundle', max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_bundles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('hotel', 'Hotel'), ('flight', 'Flight'), ('cab', 'Cab'), ('bus', 'Bus'), ('activity', 'Activity'), ('package', 'Package')], max_length=20)),
                ('product_id', models.PositiveIntegerField(help_text='FK to the booking in the respective app')),
                ('product_ref', models.CharField(blank=True, help_text='PNR, booking_ref, or public_booking_id', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.travelbundle')),
            ],
            options={
                'ordering': ['start_datetime', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('hotel', 'Hotel'), ('flight', 'Flight'), ('cab', 'Cab'), ('bus', 'Bus'), ('activity', 'Activity'), ('package', 'Package')], max_length=20)),
                ('product_id', models.PositiveIntegerField()),
                ('product_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of product at time of add-to-cart')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.cart')),
            ],
            options={
                'indexes': [models.Index(fields=['cart', 'product_type'], name='checkout_ca_cart_id_f837ee_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='travelbundle',
            index=models.Index(fields=['user', 'status'], name='checkout_tr_user_id_c81c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='bundleitem',
            index=models.Index(fields=['bundle', 'product_type'], name='checkout_bu_bundle__5e45c7_idx'),
        ),
    ]
