# Generated by Django 5.1.5 on 2026-03-20 12:56

import apps.referrals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralprofile',
            name='referral_code',
            field=models.CharField(db_index=True, default=apps.referrals.models._generate_code, max_length=12, unique=True),
        ),
    ]
