# Generated by Django 5.1.5 on 2026-03-03 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0019_add_pay_at_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(help_text="Competitor platform name (e.g. 'Booking.com', 'MakeMyTrip')", max_length=100)),
                ('source', models.CharField(blank=True, help_text='Source URL or platform identifier', max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text="Competitor's advertised price per night (INR)", max_digits=12)),
                ('date', models.DateField(help_text='Date for which this price applies')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_available', models.BooleanField(default=True, help_text='Whether the competitor has availability for this date')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_prices', to='hotels.property')),
            ],
            options={
                'ordering': ['date', 'competitor_name'],
                'indexes': [models.Index(fields=['property', 'date'], name='pricing_com_propert_e2ad78_idx'), models.Index(fields=['date', 'competitor_name'], name='pricing_com_date_b01abb_idx')],
                'unique_together': {('property', 'competitor_name', 'date')},
            },
        ),
    ]
