# Generated by Django 5.1.5 on 2026-03-06 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_alter_ratingaggregate_property_alter_review_booking_and_more'),
        ('pricing', '0001_add_competitorprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., GST 5%, GST 18%', max_length=100, unique=True)),
                ('threshold_min', models.DecimalField(decimal_places=2, default=0, help_text='Minimum per-night tariff for this slab (inclusive)', max_digits=10)),
                ('threshold_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum per-night tariff for this slab (inclusive). NULL = no upper bound.', max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=4, default=0.05, help_text='Tax rate as decimal (0.05 = 5%, 0.18 = 18%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(default='IN', max_length=50)),
            ],
            options={
                'ordering': ['threshold_min'],
            },
        ),
        migrations.AlterField(
            model_name='competitorprice',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitor_prices', to='hotels.property'),
        ),
        migrations.CreateModel(
            name='WeekendPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekend_multiplier', models.DecimalField(decimal_places=2, default=1, help_text='Multiplier for weekend nights (1.2 = 20% extra)', max_digits=4)),
                ('weekend_days', models.JSONField(default=list, help_text='ISO weekday numbers considered weekend, e.g. [5, 6] for Fri+Sat')),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekend_pricing', to='hotels.property')),
            ],
        ),
        migrations.CreateModel(
            name='EventPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(help_text='e.g., Diwali, IPL Final, New Year', max_length=200)),
                ('date', models.DateField()),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, help_text='Price multiplier for this event date', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pricing', to='hotels.property')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'date'], name='pricing_eve_propert_ec476f_idx'), models.Index(fields=['date', 'is_active'], name='pricing_eve_date_14650c_idx')],
                'unique_together': {('property', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SeasonalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Christmas Peak, Diwali Rush', max_length=100)),
                ('season_type', models.CharField(choices=[('peak', 'Peak Season'), ('high', 'High Season'), ('shoulder', 'Shoulder Season'), ('low', 'Low Season')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, help_text='Price multiplier (1.0 = no change, 1.5 = 50% increase, 0.8 = 20% discount)', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_pricing', to='hotels.property')),
            ],
            options={
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['property', 'start_date', 'end_date'], name='pricing_sea_propert_bb23e2_idx'), models.Index(fields=['is_active', 'start_date'], name='pricing_sea_is_acti_84474e_idx')],
            },
        ),
    ]
