# Generated by Django 5.1.5 on 2026-03-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0026_reviewphoto_reviewhelpfulness'),
        ('pricing', '0002_taxrule_alter_competitorprice_property_and_more'),
        ('rooms', '0010_roomtype_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancyPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_occupancy', models.PositiveIntegerField(default=2, help_text='Number of adults included in base room rate')),
                ('max_occupancy', models.PositiveIntegerField(default=3, help_text='Maximum total guests (adults + children) per room')),
                ('max_children', models.PositiveIntegerField(default=2, help_text='Maximum children allowed per room')),
                ('extra_adult_charge', models.DecimalField(decimal_places=2, default=0, help_text='Charge per extra adult per night (INR)', max_digits=10)),
                ('child_charge', models.DecimalField(decimal_places=2, default=0, help_text='Charge per child (age 5-12) per night (INR). 0 = free.', max_digits=10)),
                ('infant_charge', models.DecimalField(decimal_places=2, default=0, help_text='Charge per infant (age 0-5) per night (INR). Usually 0.', max_digits=10)),
                ('child_age_min', models.PositiveIntegerField(default=5, help_text="Minimum age to be counted as 'child' (below = infant)")),
                ('child_age_max', models.PositiveIntegerField(default=12, help_text="Maximum age to be counted as 'child' (above = adult)")),
                ('is_active', models.BooleanField(default=True)),
                ('room_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_pricing', to='rooms.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='LOSPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_nights', models.PositiveIntegerField(help_text='Minimum nights for this LOS tier (inclusive)')),
                ('max_nights', models.PositiveIntegerField(blank=True, help_text='Maximum nights for this LOS tier (inclusive). NULL = unlimited.', null=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, help_text='Price multiplier (0.90 = 10% discount, 1.0 = no change)', max_digits=4)),
                ('label', models.CharField(blank=True, help_text="Display label e.g. 'Weekly Discount', 'Monthly Rate'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='los_pricing', to='hotels.property')),
            ],
            options={
                'ordering': ['property', 'min_nights'],
                'indexes': [models.Index(fields=['property', 'min_nights', 'is_active'], name='pricing_los_propert_d81237_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_nights__gte', 1)), name='los_min_nights_positive')],
            },
        ),
    ]
