# Generated by Django 5.1.5 on 2026-03-11 14:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0027_cancellationpolicy_cancellationtier_rateplan'),
        ('pricing', '0003_occupancypricing_lospricing'),
        ('rooms', '0010_roomtype_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_type', models.CharField(choices=[('seasonal', 'Seasonal Discount'), ('last_minute', 'Last Minute'), ('long_stay', 'Long Stay'), ('weekday', 'Weekday Discount'), ('early_bird', 'Early Bird'), ('bulk', 'Bulk Booking')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('percent_off', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentage discount (e.g. 15.00 = 15% off)', max_digits=5)),
                ('flat_off', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Flat discount amount (applied per night)', max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on total discount amount', max_digits=10, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('min_nights', models.PositiveIntegerField(default=1)),
                ('min_rooms', models.PositiveIntegerField(default=1)),
                ('min_advance_days', models.PositiveIntegerField(default=0, help_text='Minimum days before check-in to qualify')),
                ('max_advance_days', models.PositiveIntegerField(default=365, help_text='Maximum days before check-in')),
                ('applicable_days', models.CharField(blank=True, default='0123456', help_text='Day numbers (0=Mon to 6=Sun) discount applies to', max_length=20)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Lower number = higher priority. When two same-type discounts overlap, highest priority wins.')),
                ('stackable', models.BooleanField(default=False, help_text='If True, can combine with other owner discounts (different types only)')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_discounts', to='hotels.property')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_discounts', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['priority', '-percent_off'],
                'indexes': [models.Index(fields=['property', 'discount_type', 'valid_from', 'valid_to'], name='pricing_pro_propert_93ada9_idx')],
            },
        ),
    ]
