# Generated by Django 5.1.5 on 2026-03-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0030_property_image_variants'),
        ('pricing', '0004_propertydiscount'),
        ('rooms', '0010_roomtype_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('multiplier', models.DecimalField(decimal_places=3, max_digits=6)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dynamic_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_at', models.DateTimeField(db_index=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_price_caches', to='hotels.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_price_caches', to='rooms.roomtype')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'room_type', 'date'], name='pricing_dyn_propert_e6cb72_idx')],
                'unique_together': {('property', 'room_type', 'date')},
            },
        ),
    ]
