# Generated by Django 5.2.11 on 2026-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_vendor',
            field=models.BooleanField(default=False, help_text='Whether this vendor has been verified by admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('traveler', 'Traveler'), ('property_owner', 'Property Owner'), ('cab_owner', 'Cab Owner'), ('bus_operator', 'Bus Operator'), ('package_provider', 'Package Provider'), ('admin', 'Admin')], default='traveler', help_text="User's primary role in the marketplace", max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.UserRole', to='accounts.role'),
        ),
    ]
