# Generated by Django 5.1.5 on 2026-03-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_role_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'Login / Register'), ('verify', 'Phone Verification')], default='login', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0, help_text='Number of failed verification attempts')),
                ('max_attempts', models.IntegerField(default=5)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', '-created_at'], name='otp_phone_purpose_idx')],
            },
        ),
    ]
