# Generated by Django 5.1.5 on 2026-03-06 17:03

from django.db import migrations, models


def fix_blank_phones(apps, schema_editor):
    """Convert empty-string phone values to NULL before adding unique constraint."""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(phone='').update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp'),
    ]

    operations = [
        # Step 1: Allow NULL first (without unique)
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        # Step 2: Fix existing data
        migrations.RunPython(fix_blank_phones, migrations.RunPython.noop),
        # Step 3: Now add unique constraint
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number must be unique. Blank stored as NULL for uniqueness.', max_length=20, null=True, unique=True),
        ),
    ]
