# Generated by Django 5.1.5 on 2026-02-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='hotels_prop_city_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotels_prop_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotels_prop_active_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotels_prop_geo_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotels_prop_trending_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotels_prop_popularity_idx',
        ),
    ]