# Generated by Search Engine Rebuild - Phase 3
# Enable PostgreSQL trigram extension for fuzzy text search

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_remove_property_hotels_prop_city_idx_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]


