# Generated by Search Engine Rebuild - Phase 3
# Add GIN trigram indexes for fast fuzzy text search

from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_enable_trigram_extension'),
        ('core', '0005_city_country_state_locationsearchindex_city_state_and_more'),
    ]

    operations = [
        # Property name trigram index
        migrations.AddIndex(
            model_name='property',
            index=GinIndex(
                fields=['name'],
                name='property_name_trgm_idx',
                opclasses=['gin_trgm_ops']
            ),
        ),
        
        # Property description trigram index (for landmark search)
        migrations.AddIndex(
            model_name='property',
            index=GinIndex(
                fields=['description'],
                name='property_desc_trgm_idx',
                opclasses=['gin_trgm_ops']
            ),
        ),
    ]


