# Generated by Search Engine Rebuild - Phase 4
# Add ranking signal fields to Property model for intelligent search ranking

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_add_search_trigram_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='search_score',
            field=models.FloatField(
                default=0.0,
                db_index=True,
                help_text='Precomputed search ranking score (0-100)'
            ),
        ),
        migrations.AddField(
            model_name='property',
            name='booking_count',
            field=models.IntegerField(
                default=0,
                db_index=True,
                help_text='Total bookings (popularity signal)'
            ),
        ),
        migrations.AddField(
            model_name='property',
            name='click_count',
            field=models.IntegerField(
                default=0,
                help_text='Total clicks from search results'
            ),
        ),
        migrations.AddField(
            model_name='property',
            name='impressions',
            field=models.IntegerField(
                default=0,
                help_text='Total search result impressions'
            ),
        ),
        migrations.AddField(
            model_name='property',
            name='conversion_rate',
            field=models.FloatField(
                default=0.0,
                help_text='Booking/Click ratio (0-1)'
            ),
        ),
        
        # Add composite index for ranking queries
        migrations.AddIndex(
            model_name='property',
            index=models.Index(
                fields=['-search_score', '-rating'],
                name='property_ranking_idx'
            ),
        ),
    ]


