# Generated by Django 5.1.15 on 2026-02-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_add_ranking_signals'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='property_name_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='property_desc_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='property_ranking_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='booking_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='click_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='conversion_rate',
        ),
        migrations.RemoveField(
            model_name='property',
            name='impressions',
        ),
        migrations.RemoveField(
            model_name='property',
            name='search_score',
        ),
    ]