# Generated by Django 5.1.15 on 2026-02-21 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_searchconfig_siteconfig_uiconfig'),
        ('hotels', '0008_remove_property_property_name_trgm_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('comfort', 'Comfort'), ('luxury', 'Luxury'), ('wellness', 'Wellness'), ('work', 'Work Facilities'), ('family', 'Family Friendly'), ('outdoor', 'Outdoor')], default='basic', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CancellationPolicyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_type', models.CharField(choices=[('non_refundable', 'Non-Refundable'), ('flexible', 'Flexible (Full Refund)'), ('moderate', 'Moderate (50% Refund)'), ('strict', 'Strict (24h Cancellation)'), ('non_refundable_with_breakfast', 'Non-Refundable (with Breakfast)')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('cancellation_hours', models.IntegerField(default=0, help_text='Hours before checkin for free cancellation')),
                ('refund_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-cancellation_hours'],
            },
        ),
        migrations.CreateModel(
            name='DistanceRangeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('max_distance_km', models.DecimalField(decimal_places=1, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['max_distance_km'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('wallet', 'Digital Wallet'), ('cash_on_arrival', 'Cash on Arrival'), ('installment', 'Installment Plan')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['method_type'],
            },
        ),
        migrations.CreateModel(
            name='PriceRangeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_price'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenityFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyBrandRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, help_text='Brand match confidence 0-1', max_digits=3)),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='PropertyCancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPaymentSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyStarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StarRatingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stars', models.IntegerField(choices=[(1, '1-Star'), (2, '2-Star'), (3, '3-Star'), (4, '4-Star'), (5, '5-Star')], unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['stars'],
            },
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='hotel_city_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['locality'], name='hotel_locality_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rating'], name='hotel_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='hotel_property_type_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='hotel_created_date_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_trending'], name='hotel_trending_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['has_free_cancellation'], name='hotel_free_cancel_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'rating'], name='hotel_city_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'property_type', 'rating'], name='hotel_city_type_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rating', '-created_at'], name='hotel_rating_date_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bookings_this_week', '-rating'], name='hotel_popularity_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricerangefilter',
            unique_together={('min_price', 'max_price')},
        ),
        migrations.AddField(
            model_name='propertyamenityfilter',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='hotels.amenityfilter'),
        ),
        migrations.AddField(
            model_name='propertyamenityfilter',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filterable_amenities', to='hotels.property'),
        ),
        migrations.AddField(
            model_name='propertybrandrelation',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='hotels.propertybrand'),
        ),
        migrations.AddField(
            model_name='propertybrandrelation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='hotels.property'),
        ),
        migrations.AddField(
            model_name='propertycancellationpolicy',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.cancellationpolicyoption'),
        ),
        migrations.AddField(
            model_name='propertycancellationpolicy',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='hotels.property'),
        ),
        migrations.AddField(
            model_name='propertypaymentsupport',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.paymentmethodtype'),
        ),
        migrations.AddField(
            model_name='propertypaymentsupport',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='hotels.property'),
        ),
        migrations.AddField(
            model_name='propertystarrating',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='star_rating', to='hotels.property'),
        ),
        migrations.AddField(
            model_name='propertystarrating',
            name='stars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.starratingoption'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyamenityfilter',
            unique_together={('property', 'amenity')},
        ),
        migrations.AlterUniqueTogether(
            name='propertybrandrelation',
            unique_together={('property', 'brand')},
        ),
        migrations.AlterUniqueTogether(
            name='propertycancellationpolicy',
            unique_together={('property', 'policy')},
        ),
        migrations.AlterUniqueTogether(
            name='propertypaymentsupport',
            unique_together={('property', 'method')},
        ),
    ]