# Generated by Django 5.1.15 on 2026-02-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_amenityfilter_cancellationpolicyoption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotel_city_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotel_locality_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotel_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotel_property_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotel_created_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotel_trending_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotel_free_cancel_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotel_city_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotel_city_type_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotel_rating_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='hotel_popularity_idx',
        ),
        migrations.DeleteModel(
            name='AmenityFilter',
        ),
        migrations.DeleteModel(
            name='CancellationPolicyOption',
        ),
        migrations.DeleteModel(
            name='PaymentMethodType',
        ),
        migrations.DeleteModel(
            name='PriceRangeFilter',
        ),
        migrations.DeleteModel(
            name='DistanceRangeFilter',
        ),
        migrations.DeleteModel(
            name='PropertyAmenityFilter',
        ),
        migrations.DeleteModel(
            name='PropertyBrand',
        ),
        migrations.DeleteModel(
            name='PropertyBrandRelation',
        ),
        migrations.DeleteModel(
            name='PropertyCancellationPolicy',
        ),
        migrations.DeleteModel(
            name='PropertyPaymentSupport',
        ),
        migrations.DeleteModel(
            name='PropertyStarRating',
        ),
        migrations.DeleteModel(
            name='StarRatingOption',
        ),
    ]
