# Generated by Django 5.2.11 on 2026-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_add_property_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agreement_file',
            field=models.FileField(blank=True, help_text='Auto-generated agreement PDF', null=True, upload_to='agreements/'),
        ),
        migrations.AddField(
            model_name='property',
            name='agreement_signed',
            field=models.BooleanField(default=False, help_text='Owner has accepted the agreement'),
        ),
        migrations.AddField(
            model_name='property',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Commission percentage owed to platform on each booking', max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', help_text='Approval status by admin', max_length=20),
        ),
    ]
