# Generated by Django 5.2.11 on 2026-02-25 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_add_commission_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=40)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('checkin', models.DateField(blank=True, null=True)),
                ('checkout', models.DateField(blank=True, null=True)),
                ('guests', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recent Hotel Search',
                'verbose_name_plural': 'Recent Hotel Searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PropertyOffer',
        ),
    ]
