# Generated by Django 5.2.11 on 2026-02-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_recentsearch_delete_propertyoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='star_category',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], default=3, help_text='Star rating category (1-5 stars)'),
        ),
    ]
