# Generated by Django 5.2.11 on 2026-02-26 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_add_star_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoApprovalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_enabled', models.BooleanField(default=True, help_text='Enable automatic approval of pending changes after X hours')),
                ('auto_approve_hours', models.IntegerField(choices=[(3, '3 hours'), (6, '6 hours'), (12, '12 hours'), (24, '24 hours')], default=6, help_text='Hours to wait before auto-approving pending changes')),
                ('notify_admins', models.BooleanField(default=True, help_text='Email admins when changes are pending')),
                ('notify_owners', models.BooleanField(default=True, help_text='Email owners when changes are approved/rejected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto Approval Settings',
                'verbose_name_plural': 'Auto Approval Settings',
            },
        ),
        migrations.CreateModel(
            name='PendingPropertyChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('field_name', models.CharField(help_text="Name of the field that was changed (e.g., 'name', 'description', 'address')", max_length=100)),
                ('field_label', models.CharField(blank=True, help_text='Human-readable field label for display', max_length=200)),
                ('old_value', models.TextField(blank=True, help_text='Previous value before change')),
                ('new_value', models.TextField(help_text='New value requested by owner')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Auto-Approved')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Optional notes from admin about approval/rejection')),
            ],
            options={
                'verbose_name': 'Pending Property Change',
                'verbose_name_plural': 'Pending Property Changes',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='recentsearch',
            old_name='guests',
            new_name='adults',
        ),
        migrations.RemoveField(
            model_name='recentsearch',
            name='location',
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category hero image for landing page', null=True, upload_to='destination_categories/'),
        ),
        migrations.AddField(
            model_name='recentsearch',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recentsearch',
            name='rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recentsearch',
            name='search_text',
            field=models.CharField(blank=True, default='', help_text='Location search text', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='e.g., Beach Vacations, Mountains Calling', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recentsearch',
            name='session_key',
            field=models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=100),
        ),
        migrations.AddIndex(
            model_name='recentsearch',
            index=models.Index(fields=['-created_at'], name='hotels_rece_created_eafdc3_idx'),
        ),
        migrations.AddIndex(
            model_name='recentsearch',
            index=models.Index(fields=['user', '-created_at'], name='hotels_rece_user_id_77401e_idx'),
        ),
        migrations.AddIndex(
            model_name='recentsearch',
            index=models.Index(fields=['session_key', '-created_at'], name='hotels_rece_session_0412b5_idx'),
        ),
        migrations.AddField(
            model_name='pendingpropertychange',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to='hotels.property'),
        ),
        migrations.AddField(
            model_name='pendingpropertychange',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pendingpropertychange',
            index=models.Index(fields=['property', 'status'], name='hotels_pend_propert_a51fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingpropertychange',
            index=models.Index(fields=['status', 'requested_at'], name='hotels_pend_status_def8b5_idx'),
        ),
    ]
