# Generated by Django 5.1.5 on 2026-02-27 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_platformsettings_service_fee_percent'),
        ('hotels', '0015_autoapprovalsettings_pendingpropertychange_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'agreement_signed'], name='property_public_listing_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='property_status_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='property_city_fk_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rating'], name='property_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_trending'], name='property_trending_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['has_free_cancellation'], name='property_free_cancel_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='property_type_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-bookings_today', '-updated_at'], name='property_popularity_idx'),
        ),
    ]
