# Generated by Django 5.1.5 on 2026-02-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_add_property_listing_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='formatted_address',
            field=models.CharField(blank=True, help_text='Full formatted address string from Google Places API', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='place_id',
            field=models.CharField(blank=True, help_text='Google Maps Place ID for autocomplete and map widget', max_length=200),
        ),
    ]
