# Generated by Django 5.1.5 on 2026-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_add_lat_lng_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pay_at_hotel',
            field=models.BooleanField(default=False, help_text='Allow guests to pay at hotel (no upfront payment required)'),
        ),
    ]
