# Generated by Django 5.1.5 on 2026-03-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0020_add_uuid_to_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of tag strings e.g. ['Couple Friendly', 'Mountain View', 'Pool View']"),
        ),
    ]
