# Generated by Django 5.1.5 on 2026-03-06 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_booking_check_in_alter_booking_check_out_and_more'),
        ('hotels', '0023_alter_property_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingaggregate',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_breakdown', to='hotels.property'),
        ),
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(help_text='One review per booking', on_delete=django.db.models.deletion.PROTECT, related_name='review', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
