# Generated by Django 5.1.5 on 2026-03-06 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_alter_ratingaggregate_property_alter_review_booking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag_type', models.CharField(choices=[('velocity', 'Review Velocity Anomaly'), ('content', 'Suspicious Content'), ('rating_anomaly', 'Rating Pattern Anomaly'), ('new_account', 'New Account Spam'), ('duplicate', 'Duplicate Content'), ('competitor_attack', 'Suspected Competitor Attack')], max_length=30)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100 risk score. >70 = auto-reject, 50-70 = manual review')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution', models.CharField(blank=True, choices=[('genuine', 'Genuine'), ('fraud', 'Fraudulent'), ('unclear', 'Unclear')], max_length=20)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='hotels.review')),
            ],
            options={
                'indexes': [models.Index(fields=['review', 'flag_type'], name='hotels_revi_review__1ac50c_idx'), models.Index(fields=['is_resolved', '-risk_score'], name='hotels_revi_is_reso_914db5_idx')],
            },
        ),
    ]
