# Generated by Django 5.1.5 on 2026-03-11 11:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0026_reviewphoto_reviewhelpfulness'),
        ('rooms', '0010_roomtype_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('policy_type', models.CharField(choices=[('free', 'Free Cancellation'), ('moderate', 'Moderate'), ('strict', 'Strict'), ('non_refundable', 'Non-Refundable'), ('custom', 'Custom')], default='moderate', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default policy for this property')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='hotels.property')),
            ],
            options={
                'verbose_name_plural': 'Cancellation Policies',
            },
        ),
        migrations.CreateModel(
            name='CancellationTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "Free cancellation", "50% refund"', max_length=100)),
                ('hours_before_checkin', models.PositiveIntegerField(help_text='Minimum hours before check-in for this tier to apply')),
                ('refund_percentage', models.DecimalField(decimal_places=2, help_text='Refund percentage (0-100)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='hotels.cancellationpolicy')),
            ],
            options={
                'ordering': ['-hours_before_checkin'],
                'unique_together': {('policy', 'hours_before_checkin')},
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_type', models.CharField(choices=[('standard', 'Standard (Refundable)'), ('non_refundable', 'Non-Refundable'), ('breakfast_included', 'Breakfast Included'), ('half_board', 'Half Board (B+D)'), ('full_board', 'Full Board (B+L+D)'), ('corporate', 'Corporate Rate'), ('long_stay', 'Long Stay Discount'), ('member', 'Member Exclusive')], default='standard', max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price_modifier_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='% adjustment from base price. -15 = 15% discount, +20 = 20% surcharge', max_digits=5)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override price per night (ignores modifier if set)', max_digits=10, null=True)),
                ('is_refundable', models.BooleanField(default=True)),
                ('includes_breakfast', models.BooleanField(default=False)),
                ('includes_lunch', models.BooleanField(default=False)),
                ('includes_dinner', models.BooleanField(default=False)),
                ('min_nights', models.PositiveIntegerField(default=1)),
                ('max_nights', models.PositiveIntegerField(default=365)),
                ('min_advance_days', models.PositiveIntegerField(default=0, help_text='Minimum days before check-in to book this plan')),
                ('max_advance_days', models.PositiveIntegerField(default=365, help_text='Maximum days before check-in to book this plan')),
                ('pay_at_hotel', models.BooleanField(default=False)),
                ('prepayment_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('cancellation_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_plans', to='hotels.cancellationpolicy')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rate_plans', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['sort_order', 'price_modifier_percent'],
                'indexes': [models.Index(fields=['room_type', 'is_active'], name='rateplan_room_active_idx'), models.Index(fields=['plan_type', 'is_active'], name='rateplan_type_active_idx')],
            },
        ),
    ]
