# Generated by Django 5.1.5 on 2026-03-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0027_cancellationpolicy_cancellationtier_rateplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='check_in_time',
            field=models.TimeField(blank=True, help_text='e.g. 14:00', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='check_out_time',
            field=models.TimeField(blank=True, help_text='e.g. 12:00', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='house_rules',
            field=models.TextField(blank=True, default='', help_text='Property rules for guests'),
        ),
    ]
