# Generated by Django 5.1.5 on 2026-03-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0029_add_savedproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_variants',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
