# Generated by Django 5.1.5 on 2026-03-19 16:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pointstransaction',
            name='loyalty_expiry_idx',
        ),
        migrations.RemoveField(
            model_name='pointstransaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pointstransaction',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='last_tier_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='lifetime_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='points_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_program_account', related_query_name='loyalty_program_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='points',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('bonus', 'Bonus')], db_index=True, max_length=20),
        ),
    ]
