# Generated by Django 5.1.5 on 2026-02-15 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
        ),
        migrations.AddField(
            model_name='cab',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cab',
            name='vehicle_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van')], default='sedan', max_length=50),
        ),
    ]