# Generated by Django 5.1.5 on 2026-02-15 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0002_cab_base_fare_cab_owner_cab_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cab Availability',
            },
        ),
        migrations.CreateModel(
            name='CabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_date', models.DateField()),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8, validators=[MinValueValidator(1)])),
                ('base_fare', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('promo_code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cab Bookings',
            },
        ),
        migrations.CreateModel(
            name='CabImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='cabs/')),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Cab Images',
            },
        ),
        migrations.CreateModel(
            name='CabType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cab',
            name='available',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='base_fare',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='cab_type',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='price_per_km',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='cab',
            name='base_price_per_km',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, validators=[MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='cab',
            name='city',
            field=models.CharField(choices=[('delhi', 'Delhi'), ('mumbai', 'Mumbai'), ('bangalore', 'Bangalore'), ('hyderabad', 'Hyderabad'), ('chennai', 'Chennai'), ('goa', 'Goa'), ('jaipur', 'Jaipur'), ('pune', 'Pune'), ('kolkata', 'Kolkata'), ('ahmedabad', 'Ahmedabad')], default='delhi', max_length=50),
        ),
        migrations.AddField(
            model_name='cab',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20),
        ),
        migrations.AddField(
            model_name='cab',
            name='name',
            field=models.CharField(default='Unnamed Cab', max_length=100),
        ),
        migrations.AddField(
            model_name='cab',
            name='seats',
            field=models.IntegerField(choices=[(2, '2 Seater'), (3, '3 Seater'), (4, '4 Seater'), (5, '5 Seater'), (6, '6 Seater'), (7, '7 Seater'), (8, '8 Seater'), (12, '12 Seater')], default=5, validators=[MinValueValidator(2), MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='cab',
            name='system_price_per_km',
            field=models.DecimalField(decimal_places=2, default=13, max_digits=8, validators=[MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='cab',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cabs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cab',
            index=models.Index(fields=['city', 'is_active'], name='cabs_cab_city_973925_idx'),
        ),
        migrations.AddIndex(
            model_name='cab',
            index=models.Index(fields=['owner', 'is_active'], name='cabs_cab_owner_i_a0eee0_idx'),
        ),
        migrations.AddField(
            model_name='cabavailability',
            name='cab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='cabs.cab'),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='cab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cabs.cab'),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cab_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cabimage',
            name='cab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cabs.cab'),
        ),
        migrations.AddIndex(
            model_name='cabavailability',
            index=models.Index(fields=['cab', 'date'], name='cabs_cabava_cab_id_9d74d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cabavailability',
            unique_together={('cab', 'date')},
        ),
        migrations.AddIndex(
            model_name='cabbooking',
            index=models.Index(fields=['user', 'booking_date'], name='cabs_cabboo_user_id_ac2786_idx'),
        ),
        migrations.AddIndex(
            model_name='cabbooking',
            index=models.Index(fields=['cab', 'booking_date'], name='cabs_cabboo_cab_id_b131e1_idx'),
        ),
    ]