# Generated by Django 5.1.5 on 2026-02-15 12:24

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0003_cabavailability_cabbooking_cabimage_cabtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbooking',
            name='booking_date',
            field=models.DateField(validators=[apps.core.validators.validate_future_date]),
        ),
    ]