# Generated by Django 5.1.5 on 2026-02-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0004_alter_cabbooking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='public_booking_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]