# Generated by Django 5.1.5 on 2026-02-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0005_cabbooking_public_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]