# Generated by Django 5.1.5 on 2026-03-06 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0006_cabbooking_idempotency_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_cabs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='cab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cabs.cab'),
        ),
    ]
