# Generated by Django 5.1.5 on 2026-03-10 03:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0007_alter_cab_owner_alter_cabbooking_cab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='cab_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabs', to='cabs.cabtype'),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='drop_address',
            field=models.CharField(blank=True, help_text='Drop-off location address', max_length=255),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='drop_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='drop_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='pickup_address',
            field=models.CharField(blank=True, help_text='Pickup location address', max_length=255),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='surge_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Surge multiplier at time of booking', max_digits=4),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cab_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CabPriceBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promo_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_breakdown', to='cabs.cabbooking')),
            ],
            options={
                'verbose_name_plural': 'Cab Price Breakdowns',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('license_number', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(choices=[('delhi', 'Delhi'), ('mumbai', 'Mumbai'), ('bangalore', 'Bangalore'), ('hyderabad', 'Hyderabad'), ('chennai', 'Chennai'), ('goa', 'Goa'), ('jaipur', 'Jaipur'), ('pune', 'Pune'), ('kolkata', 'Kolkata'), ('ahmedabad', 'Ahmedabad')], max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('offline', 'Offline'), ('break', 'On Break')], default='offline', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('cab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='cabs.cab')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='cabs.driver'),
        ),
        migrations.CreateModel(
            name='SurgePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(choices=[('delhi', 'Delhi'), ('mumbai', 'Mumbai'), ('bangalore', 'Bangalore'), ('hyderabad', 'Hyderabad'), ('chennai', 'Chennai'), ('goa', 'Goa'), ('jaipur', 'Jaipur'), ('pune', 'Pune'), ('kolkata', 'Kolkata'), ('ahmedabad', 'Ahmedabad')], db_index=True, max_length=50)),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Monday..6=Sunday, null=all days', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_hour', models.IntegerField(default=0, help_text='Start hour (24h format)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('end_hour', models.IntegerField(default=23, help_text='End hour (24h format)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Surge multiplier (1.0=no surge, 2.0=2x)', max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, help_text="e.g. 'Peak morning hours', 'Rain surge', 'Event surge'", max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Surge Pricing Rules',
                'ordering': ['-multiplier'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='cabs_surgep_city_8e3d78_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['city', 'status'], name='cabs_driver_city_487087_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['cab'], name='cabs_driver_cab_id_7df9a7_idx'),
        ),
    ]
