# Generated by Django 5.1.5 on 2026-03-11 09:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0008_cab_cab_type_cabbooking_drop_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trip_status', models.CharField(choices=[('driver_assigned', 'Driver Assigned'), ('en_route_pickup', 'En Route to Pickup'), ('arrived_pickup', 'Arrived at Pickup'), ('trip_started', 'Trip Started'), ('trip_completed', 'Trip Completed'), ('trip_cancelled', 'Trip Cancelled')], default='driver_assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('trip_started_at', models.DateTimeField(blank=True, null=True)),
                ('trip_completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, help_text='ETA in minutes', null=True)),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('otp_code', models.CharField(blank=True, help_text='Ride start OTP', max_length=6)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='cabs.cabbooking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='cabs.driver')),
            ],
            options={
                'verbose_name_plural': 'Cab Trips',
                'indexes': [models.Index(fields=['driver', 'trip_status'], name='cabs_cabtri_driver__428027_idx'), models.Index(fields=['trip_status', '-assigned_at'], name='cabs_cabtri_trip_st_14ee47_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('safety_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cleanliness_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('punctuality_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_review', to='cabs.cabbooking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cabs.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cab_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('booking', 'user')},
            },
        ),
    ]
