# Generated by Django 5.1.5 on 2026-03-11 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0009_cabtrip_driverreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('searching', 'Searching for Driver'), ('driver_found', 'Driver Found'), ('driver_accepted', 'Driver Accepted'), ('no_drivers', 'No Drivers Available'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='searching', max_length=20)),
                ('pickup_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('pickup_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('drop_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('drop_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('search_radius_km', models.FloatField(default=5.0)),
                ('drivers_contacted', models.IntegerField(default=0)),
                ('match_attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('estimated_pickup_minutes', models.IntegerField(blank=True, null=True)),
                ('estimated_trip_minutes', models.IntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='cabs.cabbooking')),
                ('matched_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_requests', to='cabs.driver')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='dispatch_status_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('heading', models.FloatField(default=0, help_text='Compass heading in degrees')),
                ('speed_kmh', models.FloatField(default=0)),
                ('accuracy_meters', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to='cabs.driver')),
            ],
            options={
                'indexes': [models.Index(fields=['last_updated'], name='driverloc_updated_idx')],
            },
        ),
    ]
