# Generated by Django 5.1.15 on 2026-02-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_search_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchindex',
            new_name='search_sear_type_5c4e06_idx',
            old_name='search_se_type_2d4980_idx',
        ),
        migrations.RenameIndex(
            model_name='searchindex',
            new_name='search_sear_slug_723a51_idx',
            old_name='search_se_slug_6ab32f_idx',
        ),
    ]
