# Generated by Django 5.1.5 on 2026-03-06 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_alter_ratingaggregate_property_alter_review_booking_and_more'),
        ('search', '0002_rename_search_se_type_2d4980_idx_search_sear_type_5c4e06_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('property_name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('property_type', models.CharField(db_index=True, max_length=80)),
                ('city_id', models.IntegerField(db_index=True)),
                ('city_name', models.CharField(db_index=True, max_length=100)),
                ('locality_name', models.CharField(blank=True, max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('star_category', models.IntegerField(default=3)),
                ('price_min', models.DecimalField(decimal_places=2, default=0, help_text='Cheapest room type base price', max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, default=0, help_text='Most expensive room type base price', max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('review_score', models.DecimalField(decimal_places=1, default=0, help_text='Weighted review score for ranking', max_digits=3)),
                ('popularity_score', models.IntegerField(default=0)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('has_free_cancellation', models.BooleanField(db_index=True, default=True)),
                ('pay_at_hotel', models.BooleanField(db_index=True, default=False)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenity names for faceted search')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Property tags (Couple Friendly, Mountain View, etc.)')),
                ('featured_image_url', models.URLField(blank=True)),
                ('has_availability', models.BooleanField(db_index=True, default=True, help_text='Has at least one room available in next 30 days')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index_entry', to='hotels.property')),
            ],
            options={
                'indexes': [models.Index(fields=['city_id', 'price_min'], name='search_prop_city_id_78db27_idx'), models.Index(fields=['city_name', 'rating'], name='search_prop_city_na_0313f5_idx'), models.Index(fields=['price_min', 'rating'], name='search_prop_price_m_bb7cb5_idx'), models.Index(fields=['popularity_score', '-rating'], name='search_prop_popular_e2a8e1_idx'), models.Index(fields=['is_trending', '-popularity_score'], name='search_prop_is_tren_2972f4_idx'), models.Index(fields=['has_free_cancellation', 'price_min'], name='search_prop_has_fre_ccf1c6_idx'), models.Index(fields=['star_category', 'price_min'], name='search_prop_star_ca_ec664a_idx'), models.Index(fields=['latitude', 'longitude'], name='search_prop_latitud_638bce_idx')],
            },
        ),
    ]
