# Generated by Django 5.1.5 on 2026-03-07 08:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0025_reviewfraudflag'),
        ('search', '0003_propertysearchindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysearchindex',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='propertysearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_fts_gin_idx'),
        ),
    ]
