# Generated by Django 5.1.5 on 2026-03-07 14:02

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0025_reviewfraudflag'),
        ('search', '0004_propertysearchindex_search_vector_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='propertysearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['amenities'], name='search_amenities_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='propertysearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='search_tags_gin_idx'),
        ),
    ]
