# Generated by Django 5.1.5 on 2026-03-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0025_reviewfraudflag'),
        ('search', '0005_propertysearchindex_search_amenities_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysearchindex',
            name='available_rooms',
            field=models.IntegerField(default=0, help_text='Total rooms available in next 30 days (for urgency signals)'),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='ranking_score',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, help_text='Pre-computed ranking score from enhanced_ranking engine', max_digits=8),
        ),
        migrations.AddIndex(
            model_name='propertysearchindex',
            index=models.Index(fields=['-ranking_score', 'city_id'], name='search_prop_ranking_1f35e4_idx'),
        ),
    ]
