# Generated by Django 5.1.5 on 2026-03-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_propertysearchindex_available_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysearchindex',
            name='cashback_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max cashback available', max_digits=10),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='deal_score',
            field=models.IntegerField(default=0, help_text='0-100 deal quality score'),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current discount % vs rack rate', max_digits=5),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance from city center in km', max_digits=6),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='has_breakfast',
            field=models.BooleanField(db_index=True, default=False, help_text='At least one room type includes breakfast'),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='rack_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rack/strikethrough price for discount display', max_digits=10),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='recent_bookings',
            field=models.IntegerField(default=0, help_text='Bookings in last 24h (social proof)'),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='rooms_left',
            field=models.IntegerField(default=0, help_text='Rooms left for nearest check-in date (urgency)'),
        ),
    ]
