# Generated by Django 5.1.5 on 2026-03-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_propertysearchindex_cashback_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysearchindex',
            name='click_through_rate',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, help_text='CTR = clicks / impressions (updated by Celery task)', max_digits=5),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='total_bookings',
            field=models.PositiveIntegerField(default=0, help_text='Total confirmed bookings (for conversion rate)'),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='total_clicks',
            field=models.PositiveIntegerField(default=0, help_text='Total clicks from search results'),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='total_impressions',
            field=models.PositiveIntegerField(default=0, help_text='Total search result impressions'),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='total_views',
            field=models.PositiveIntegerField(default=0, help_text='Total detail page views'),
        ),
    ]
