# Generated by Django 5.1.5 on 2026-03-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_propertysearchindex_click_through_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysearchindex',
            name='availability_reliability',
            field=models.DecimalField(decimal_places=4, default=1, help_text='How often rooms are actually available when listed (0-1)', max_digits=5),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='cancellation_rate',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, help_text='Cancellation rate = cancellations / total bookings (lower is better)', max_digits=5),
        ),
        migrations.AddField(
            model_name='propertysearchindex',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=15, help_text='OTA commission % for margin scoring', max_digits=5),
        ),
    ]
