# Generated by Django 5.1.5 on 2026-03-10 14:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_propertysearchindex_availability_reliability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('preferred_cities', models.JSONField(default=list, help_text='City IDs ordered by booking frequency')),
                ('recent_search_cities', models.JSONField(default=list, help_text='Recent search destination names (last 30 days)')),
                ('avg_booking_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average booking amount', max_digits=10)),
                ('min_price_range', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_price_range', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('preferred_star', models.PositiveIntegerField(blank=True, help_text='Most frequently booked star category', null=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('total_cancellations', models.PositiveIntegerField(default=0)),
                ('booking_frequency_days', models.FloatField(default=0.0, help_text='Average days between bookings')),
                ('traveller_type', models.CharField(blank=True, help_text='Most frequent traveler type from reviews', max_length=20)),
                ('last_aggregated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='usp_user_idx')],
            },
        ),
    ]
