# Generated by Django 5.1.5 on 2026-03-10 03:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_booking_id', models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, unique=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('adults', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('children', models.PositiveIntegerField(default=0)),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('child_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('group_discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount for group bookings (5+ travelers)', max_digits=12)),
                ('promo_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promo_code', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('partially_paid', 'Partially Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='packages.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageBookingTraveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('traveler_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('id_proof_type', models.CharField(blank=True, max_length=50)),
                ('id_proof_number', models.CharField(blank=True, max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='packages.packagebooking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('total_slots', models.PositiveIntegerField(default=20)),
                ('booked_slots', models.PositiveIntegerField(default=0)),
                ('is_guaranteed', models.BooleanField(default=False, help_text='Departure guaranteed regardless of bookings')),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='packages.package')),
            ],
            options={
                'ordering': ['departure_date'],
                'unique_together': {('package', 'departure_date')},
            },
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='packages.packagedeparture'),
        ),
        migrations.CreateModel(
            name='PackageSeasonalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season_name', models.CharField(choices=[('peak', 'Peak Season'), ('offpeak', 'Off-Peak Season'), ('festival', 'Festival Season'), ('monsoon', 'Monsoon Discount')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('child_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per child (0 = free)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_prices', to='packages.package')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='packagebooking',
            index=models.Index(fields=['user', 'status'], name='packages_pa_user_id_642d57_idx'),
        ),
        migrations.AddIndex(
            model_name='packagebooking',
            index=models.Index(fields=['package', 'status'], name='packages_pa_package_e1f96a_idx'),
        ),
        migrations.AddIndex(
            model_name='packageseasonalprice',
            index=models.Index(fields=['package', 'start_date', 'end_date'], name='packages_pa_package_b9d5ef_idx'),
        ),
    ]
