# Generated by Django 5.1.5 on 2026-03-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_packagebooking_packagebookingtraveler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon_type', models.CharField(choices=[('airport_transfer', 'Airport Transfer'), ('local_sightseeing', 'Local Sightseeing'), ('adventure', 'Adventure Activity'), ('spa_wellness', 'Spa & Wellness'), ('photography', 'Photography'), ('meals_upgrade', 'Meals Upgrade'), ('travel_insurance', 'Travel Insurance'), ('guide_private', 'Private Guide'), ('room_upgrade', 'Room Upgrade'), ('other', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_type', models.CharField(choices=[('per_person', 'Per Person'), ('per_booking', 'Per Booking (flat)'), ('per_day', 'Per Day')], default='per_person', max_length=15)),
                ('max_quantity', models.PositiveIntegerField(default=1, help_text='Max units per booking (e.g., 2 sightseeing tours)')),
                ('is_popular', models.BooleanField(default=False, help_text='Show as recommended add-on')),
                ('bundle_discount_pct', models.DecimalField(decimal_places=2, default=0, help_text='Discount % when bundled with 2+ add-ons', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='packages.package')),
            ],
            options={
                'ordering': ['-is_popular', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PackageBookingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Snapshot at booking time', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_selections', to='packages.packageaddon')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_addons', to='packages.packagebooking')),
            ],
        ),
        migrations.AddIndex(
            model_name='packageaddon',
            index=models.Index(fields=['package', 'addon_type'], name='packages_pa_package_e32777_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='packagebookingaddon',
            unique_together={('booking', 'addon')},
        ),
    ]
