# Generated by Django 5.1.5 on 2026-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operation_type', models.CharField(choices=[('booking_failed', 'Booking Failed'), ('booking_created', 'Booking Created'), ('payment_failed', 'Payment Failed'), ('payment_initiated', 'Payment Initiated'), ('coupon_applied', 'Coupon Applied'), ('coupon_rejected', 'Coupon Rejected'), ('inventory_sync', 'Inventory Sync'), ('price_calculated', 'Price Calculated')], max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Operation Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['operation_type', 'status', '-timestamp'], name='core_operat_operati_005399_idx'), models.Index(fields=['timestamp'], name='core_operat_timesta_b53812_idx')],
            },
        ),
    ]