# Generated by Django 5.1.5 on 2026-02-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel_id', models.PositiveIntegerField(db_index=True)),
                ('issue_type', models.CharField(choices=[('mismatch', 'Inventory Mismatch'), ('sync_failed', 'Sync Failed'), ('price_anomaly', 'Price Anomaly'), ('availability_zero', 'Zero Availability'), ('stale_data', 'Stale Data')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['hotel_id', 'is_resolved'], name='core_invent_hotel_i_aa27a3_idx'), models.Index(fields=['severity', 'is_resolved'], name='core_invent_severit_d9de8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operation_type', models.CharField(choices=[('booking_create', 'Booking Creation'), ('search', 'Search'), ('payment', 'Payment'), ('inventory_sync', 'Inventory Sync'), ('price_calculation', 'Price Calculation')], db_index=True, max_length=50)),
                ('duration_ms', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('timeout', 'Timeout'), ('error', 'Error')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['operation_type', 'start_time'], name='core_perfor_operati_419f65_idx'), models.Index(fields=['status', 'start_time'], name='core_perfor_status_ea8ddc_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('confirmed_bookings', models.PositiveIntegerField(default=0)),
                ('failed_bookings', models.PositiveIntegerField(default=0)),
                ('pending_bookings', models.PositiveIntegerField(default=0)),
                ('bookings_per_minute', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('failures_per_minute', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('error_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('inventory_mismatches', models.PositiveIntegerField(default=0)),
                ('rooms_available', models.PositiveIntegerField(default=0)),
                ('hotels_with_issues', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('revenue_per_booking', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_response_time_ms', models.PositiveIntegerField(default=0)),
                ('cache_hit_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('snapshot_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-snapshot_time'],
                'indexes': [models.Index(fields=['-snapshot_time'], name='core_system_snapsho_34f92c_idx')],
            },
        ),
    ]