# Generated by Django 5.1.5 on 2026-02-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inventoryhealthcheck_performancelog_systemmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='operation_type',
            field=models.CharField(choices=[('booking_failed', 'Booking Failed'), ('booking_created', 'Booking Created'), ('payment_failed', 'Payment Failed'), ('payment_initiated', 'Payment Initiated'), ('coupon_applied', 'Coupon Applied'), ('coupon_rejected', 'Coupon Rejected'), ('inventory_sync', 'Inventory Sync'), ('price_calculated', 'Price Calculated'), ('mapping_decision', 'Mapping Decision'), ('fraud_triggered', 'Fraud Triggered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='performancelog',
            name='operation_type',
            field=models.CharField(choices=[('booking_create', 'Booking Creation'), ('search', 'Search'), ('payment', 'Payment'), ('inventory_sync', 'Inventory Sync'), ('price_calculation', 'Price Calculation'), ('inventory_lock', 'Inventory Lock')], db_index=True, max_length=50),
        ),
    ]