# Generated by Django 5.1.5 on 2026-02-17 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_operationlog_operation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='Icon class name', max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('is_trending', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0, help_text='Higher = shows first')),
                ('search_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-priority', '-search_count'],
                'indexes': [models.Index(fields=['slug'], name='core_destin_slug_9b18ca_idx'), models.Index(fields=['-is_trending', '-priority'], name='core_destin_is_tren_a91f45_idx')],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('offer_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FLAT', 'Flat Amount Off'), ('DEAL', 'Special Deal')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'ordering': ['-priority', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('CITY', 'City'), ('AREA', 'Area'), ('LANDMARK', 'Landmark'), ('PROPERTY', 'Property Name'), ('DESTINATION', 'Destination')], max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('normalized_name', models.CharField(db_index=True, max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('search_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-search_count', 'name'],
                'indexes': [models.Index(fields=['normalized_name'], name='core_search_normali_67c9ae_idx'), models.Index(fields=['search_type', '-search_count'], name='core_search_search__0b8f1e_idx')],
            },
        ),
    ]