# Generated by Django 5.1.5 on 2026-02-17 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_destination_offer_searchindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='CTXCR code for search', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('alternate_names', models.TextField(blank=True, help_text='Comma-separated aliases')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ne_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ne_lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('sw_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('sw_lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('hotel_count', models.IntegerField(default=0)),
                ('popularity_score', models.IntegerField(default=0, help_text='Based on search volume')),
                ('is_top_destination', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'indexes': [models.Index(fields=['code', 'is_active'], name='core_countr_code_8987a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='State code', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='LocationSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('country', 'Country'), ('state', 'State'), ('city', 'City'), ('locality', 'Locality'), ('hotel', 'Hotel'), ('landmark', 'Landmark')], max_length=20)),
                ('entity_id', models.IntegerField(help_text='FK to actual entity')),
                ('display_name', models.CharField(max_length=200)),
                ('search_text', models.TextField(help_text='Normalized text for fuzzy search')),
                ('alternate_names', models.TextField(blank=True)),
                ('search_score', models.IntegerField(default=0, help_text='Higher = better ranking')),
                ('search_count', models.IntegerField(default=0, help_text='How many times searched')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Search → booking %', max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('is_clickable', models.BooleanField(default=True, help_text='Can user click to see results')),
                ('is_active', models.BooleanField(default=True)),
                ('context_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_entries', to='core.city')),
                ('context_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_entries', to='core.country')),
                ('context_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_entries', to='core.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.state'),
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('hotel_count', models.IntegerField(default=0)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('popularity_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('landmarks', models.TextField(blank=True, help_text='Comma-separated nearby landmarks')),
                ('locality_type', models.CharField(choices=[('business', 'Business District'), ('tourist', 'Tourist Area'), ('residential', 'Residential'), ('airport', 'Near Airport'), ('beach', 'Beach Area'), ('hill_station', 'Hill Station')], default='tourist', max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='core.city')),
            ],
            options={
                'verbose_name_plural': 'Localities',
                'indexes': [models.Index(fields=['city', 'is_active'], name='core_locali_city_id_cf6416_idx'), models.Index(fields=['-popularity_score'], name='core_locali_popular_177991_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('cities', models.ManyToManyField(related_name='regions', to='core.city')),
            ],
            options={
                'indexes': [models.Index(fields=['code', 'is_active'], name='core_region_code_7993f9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country', 'is_active'], name='core_state_country_5fd311_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['code'], name='core_state_code_bd3773_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'code')},
        ),
        migrations.AddIndex(
            model_name='locationsearchindex',
            index=models.Index(fields=['entity_type', 'entity_id'], name='core_locati_entity__29cfad_idx'),
        ),
        migrations.AddIndex(
            model_name='locationsearchindex',
            index=models.Index(fields=['search_text'], name='core_locati_search__4d08af_idx'),
        ),
        migrations.AddIndex(
            model_name='locationsearchindex',
            index=models.Index(fields=['-search_score', '-search_count'], name='core_locati_search__d3344f_idx'),
        ),
        migrations.AddIndex(
            model_name='locationsearchindex',
            index=models.Index(fields=['context_city', 'is_active'], name='core_locati_context_afe518_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['code'], name='core_city_code_1471aa_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'is_active'], name='core_city_state_i_002a53_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['-popularity_score'], name='core_city_popular_dfeb8a_idx'),
        ),
    ]