# Generated by Search Engine Rebuild - Phase 3
# Add GIN trigram indexes to City and Locality for autocomplete

from django.contrib.postgres.indexes import GinIndex
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_city_country_state_locationsearchindex_city_state_and_more'),
    ]

    operations = [
        # City name trigram index for autocomplete
        migrations.AddIndex(
            model_name='city',
            index=GinIndex(
                fields=['name'],
                name='city_name_trgm_idx',
                opclasses=['gin_trgm_ops']
            ),
        ),
        
        # Locality name trigram index for autocomplete
        migrations.AddIndex(
            model_name='locality',
            index=GinIndex(
                fields=['name'],
                name='locality_name_trgm_idx',
                opclasses=['gin_trgm_ops']
            ),
        ),
    ]


