# Generated by Django 5.1.15 on 2026-02-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_location_trigram_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='city',
            name='city_name_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='locality',
            name='locality_name_trgm_idx',
        ),
    ]