# Generated by Django 5.1.15 on 2026-02-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_city_city_name_trgm_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_results_per_page', models.PositiveIntegerField(default=20)),
                ('max_price_range', models.PositiveIntegerField(default=100000, help_text='Maximum price filter in INR')),
                ('search_radius_km', models.PositiveIntegerField(default=50, help_text='Default search radius for location-based searches')),
                ('enable_autocomplete', models.BooleanField(default=True)),
                ('autocomplete_min_chars', models.PositiveIntegerField(default=2)),
                ('autocomplete_max_results', models.PositiveIntegerField(default=10)),
                ('max_advance_booking_days', models.PositiveIntegerField(default=180, help_text='How far in advance can users book')),
                ('min_checkin_hours', models.PositiveIntegerField(default=2, help_text='Minimum hours before check-in for same-day bookings')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Configuration',
                'verbose_name_plural': 'Search Configuration',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ZygoTrip', max_length=100)),
                ('site_tagline', models.CharField(default='Your Travel Companion', max_length=200)),
                ('support_email', models.EmailField(default='support@zygotrip.com', max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('enable_hotels', models.BooleanField(default=True)),
                ('enable_buses', models.BooleanField(default=True)),
                ('enable_cabs', models.BooleanField(default=True)),
                ('enable_trains', models.BooleanField(default=True)),
                ('enable_packages', models.BooleanField(default=True)),
                ('enable_flights', models.BooleanField(default=False)),
                ('default_currency', models.CharField(default='INR', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='GST/Tax percentage', max_digits=5)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default="We're performing scheduled maintenance. Check back soon!")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='UIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Plan Your Perfect Trip', max_length=200)),
                ('hero_subtitle', models.TextField(default='Book hotels, buses, cabs and more with ease')),
                ('show_hero', models.BooleanField(default=True)),
                ('featured_section_title', models.CharField(default='Featured Destinations', max_length=100)),
                ('show_featured_section', models.BooleanField(default=True)),
                ('homepage_results_count', models.PositiveIntegerField(default=12)),
                ('show_ratings', models.BooleanField(default=True)),
                ('show_reviews_count', models.BooleanField(default=True)),
                ('show_amenities', models.BooleanField(default=True)),
                ('show_distances', models.BooleanField(default=True)),
                ('empty_state_title', models.CharField(default='No results found', max_length=100)),
                ('empty_state_message', models.TextField(default='Try adjusting your filters or search criteria')),
                ('empty_state_cta', models.CharField(default='Clear Filters', max_length=50)),
                ('enable_animations', models.BooleanField(default=True)),
                ('enable_sticky_search', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UI Configuration',
                'verbose_name_plural': 'UI Configuration',
            },
        ),
    ]