# Generated by Django 5.1.15 on 2026-02-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_searchconfig_siteconfig_uiconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchConfig',
        ),
        migrations.DeleteModel(
            name='SiteConfig',
        ),
        migrations.DeleteModel(
            name='UIConfig',
        ),
    ]
