# Generated by Django 5.1.15 on 2026-02-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_searchconfig_delete_siteconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug for routing', max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug for routing', max_length=120, null=True),
        ),
    ]
