# Generated by Django 5.2.11 on 2026-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_city_slug_locality_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_property_commission', models.DecimalField(decimal_places=2, default=10.0, help_text='Default commission % for hotel/property owners', max_digits=5)),
                ('default_cab_commission', models.DecimalField(decimal_places=2, default=15.0, help_text='Default commission % for cab owners', max_digits=5)),
                ('default_bus_commission', models.DecimalField(decimal_places=2, default=12.0, help_text='Default commission % for bus operators', max_digits=5)),
                ('default_package_commission', models.DecimalField(decimal_places=2, default=20.0, help_text='Default commission % for package providers', max_digits=5)),
                ('require_agreement_signature', models.BooleanField(default=True, help_text='Require vendor to sign agreement before listing is public')),
                ('platform_name', models.CharField(default='Zygotrip', help_text='Platform name for agreements and communications', max_length=100)),
                ('support_email', models.EmailField(default='support@zygotrip.com', help_text='Support email for vendor communications', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
