# Generated by Django 5.2.11 on 2026-02-24 15:44

from django.db import migrations


def create_default_settings(apps, schema_editor):
	"""Create the default singleton PlatformSettings instance"""
	PlatformSettings = apps.get_model('core', 'PlatformSettings')
	
	# Create singleton instance with default values
	PlatformSettings.objects.get_or_create(
		pk=1,
		defaults={
			'platform_name': 'Zygotrip',
			'support_email': 'support@zygotrip.com',
			'default_property_commission': '10.00',
			'default_cab_commission': '15.00',
			'default_bus_commission': '12.00',
			'default_package_commission': '20.00',
			'require_agreement_signature': True,
		}
	)


def delete_settings(apps, schema_editor):
	"""Reverse: delete the singleton instance"""
	PlatformSettings = apps.get_model('core', 'PlatformSettings')
	PlatformSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_platform_settings'),
    ]

    operations = [
        migrations.RunPython(create_default_settings, delete_settings),
    ]

