# Generated by Django 5.2.11 on 2026-02-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_create_default_platform_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='service_fee_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Service fee % applied to bookings (e.g., 10.00 for 10%)', max_digits=5),
        ),
    ]
