# Generated by Django 5.1.5 on 2026-03-06 15:49

import apps.core.referral
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(unique=True)),
                ('total_searches', models.IntegerField(default=0)),
                ('total_property_views', models.IntegerField(default=0)),
                ('total_booking_contexts', models.IntegerField(default=0)),
                ('total_bookings_confirmed', models.IntegerField(default=0)),
                ('total_bookings_cancelled', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_payments_failed', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('avg_booking_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'db_table': 'core_daily_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('available_points', models.IntegerField(default=0)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_loyalty_account',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('txn_type', models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('expire', 'Expire'), ('bonus', 'Bonus')], max_length=10)),
                ('points', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.loyaltyaccount')),
            ],
            options={
                'db_table': 'core_loyalty_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('referral_code', models.CharField(db_index=True, default=apps.core.referral._generate_referral_code, max_length=10, unique=True)),
                ('total_referrals', models.IntegerField(default=0)),
                ('successful_referrals', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_referrals', models.IntegerField(default=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_referral_profile',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('search', 'Search'), ('property_view', 'Property View'), ('room_select', 'Room Select'), ('booking_context_created', 'Booking Context Created'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('review_submitted', 'Review Submitted'), ('promo_applied', 'Promo Applied'), ('loyalty_redeemed', 'Loyalty Redeemed')], db_index=True, max_length=30)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('property_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_analytics_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='analytics_type_time_idx'), models.Index(fields=['user', '-created_at'], name='analytics_user_time_idx'), models.Index(fields=['session_id', '-created_at'], name='analytics_session_idx')],
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('action_taken', models.CharField(choices=[('flag', 'Flag for Review'), ('block', 'Block'), ('require_verification', 'Require Verification'), ('allow', 'Allow')], default='flag', max_length=25)),
                ('reason', models.TextField()),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_resolutions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_fraud_flag',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='fraud_user_idx'), models.Index(fields=['ip_address', '-created_at'], name='fraud_ip_idx'), models.Index(fields=['resolved', '-created_at'], name='fraud_unresolved_idx')],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('referral_code', models.CharField(db_index=True, max_length=10)),
                ('referee_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed_up', 'Signed Up'), ('completed', 'Completed'), ('rewarded', 'Rewarded')], default='pending', max_length=15)),
                ('referrer_reward', models.IntegerField(default=0, help_text='Loyalty points awarded to referrer')),
                ('referee_reward', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wallet credit given to referee', max_digits=10)),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_referral',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('referrer', 'referee_email'), name='unique_referral_per_email')],
            },
        ),
    ]
