# Generated by Django 5.1.5 on 2026-03-06 17:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_loyalty_referral_fraud_analytics'),
        ('hotels', '0025_reviewfraudflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorRateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('undercut', 'Competitor Undercut'), ('parity_violation', 'Rate Parity Violation'), ('price_opportunity', 'Pricing Opportunity')], max_length=30)),
                ('competitor_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('our_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('competitor_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difference_pct', models.DecimalField(decimal_places=1, max_digits=5)),
                ('recommendation', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_alerts', to='hotels.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'is_resolved', '-created_at'], name='core_compet_propert_8e09e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('predicted_occupancy', models.DecimalField(decimal_places=2, help_text='Predicted occupancy rate 0.00-1.00', max_digits=5)),
                ('predicted_demand_score', models.IntegerField(default=50, help_text='0-100 demand intensity score')),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Prediction confidence 0.00-1.00', max_digits=4)),
                ('factors', models.JSONField(blank=True, default=dict, help_text='Contributing factors: seasonality, day_of_week, events, trend')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='hotels.property')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'predicted_demand_score'], name='core_demand_date_bdb6b5_idx'), models.Index(fields=['property', 'date'], name='core_demand_propert_fc5783_idx')],
                'unique_together': {('property', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HotelQualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('overall_score', models.IntegerField(default=50)),
                ('guest_satisfaction_score', models.IntegerField(default=50)),
                ('pricing_competitiveness', models.IntegerField(default=50)),
                ('response_rate_score', models.IntegerField(default=50)),
                ('photo_quality_score', models.IntegerField(default=50)),
                ('listing_completeness', models.IntegerField(default=50)),
                ('cancellation_score', models.IntegerField(default=50)),
                ('repeat_guest_rate', models.IntegerField(default=0)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('is_value_pick', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_score', to='hotels.property')),
            ],
            options={
                'indexes': [models.Index(fields=['-overall_score'], name='core_hotelq_overall_bba898_idx'), models.Index(fields=['is_top_rated', '-overall_score'], name='core_hotelq_is_top__3e2816_idx'), models.Index(fields=['is_value_pick', '-overall_score'], name='core_hotelq_is_valu_021bfd_idx')],
            },
        ),
    ]
