# Generated by Django 5.1.5 on 2026-03-06 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_competitorratealert_demandforecast_hotelqualityscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accept_language', models.CharField(blank=True, max_length=200)),
                ('screen_resolution', models.CharField(blank=True, max_length=50)),
                ('timezone_offset', models.IntegerField(blank=True, help_text='Minutes from UTC', null=True)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('is_mobile', models.BooleanField(default=False)),
                ('canvas_hash', models.CharField(blank=True, help_text='Canvas fingerprint from JS', max_length=64)),
                ('webgl_hash', models.CharField(blank=True, help_text='WebGL renderer hash', max_length=64)),
                ('fraud_score', models.IntegerField(default=0, help_text='0-100, higher = more suspicious')),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('flag_reasons', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['fingerprint_hash', 'user'], name='core_device_fingerp_fe52e0_idx'), models.Index(fields=['ip_address', '-created_at'], name='core_device_ip_addr_be8e65_idx'), models.Index(fields=['is_flagged', '-fraud_score'], name='core_device_is_flag_b8ba29_idx')],
            },
        ),
    ]
