# Generated by Django 5.1.5 on 2026-03-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_performanceindex_adminipallowlist_fraudrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, help_text='Unique flag name (e.g. "enable_new_checkout")', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=False, help_text='Master switch — if False, flag is off for everyone')),
                ('rollout_percentage', models.PositiveIntegerField(default=100, help_text='0-100: percentage of users who see this flag as enabled')),
                ('allowed_groups', models.JSONField(blank=True, default=list, help_text='List of Django group names that can see this flag (empty = all groups)')),
                ('allowed_users', models.JSONField(blank=True, default=list, help_text='List of user IDs that always see this flag (override rollout)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value data (e.g. variant config)')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-disable after this date (cleanup)', null=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['name'],
            },
        ),
    ]
