# Generated by Django 5.1.5 on 2026-03-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_featureflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.CharField(blank=True, help_text='District name for sub-city search', max_length=100),
        ),
    ]
