# Generated by Django 5.1.5 on 2026-03-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_district_to_city'),
        ('hotels', '0026_reviewphoto_reviewhelpfulness'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoindex',
            name='geohash4',
            field=models.CharField(blank=True, db_index=True, help_text='Geohash precision 4 (~39km) for region-level clustering', max_length=4),
        ),
        migrations.AddField(
            model_name='geoindex',
            name='geohash6',
            field=models.CharField(blank=True, db_index=True, help_text='Geohash precision 6 (~1.2km) for spatial prefix queries', max_length=6),
        ),
        migrations.AddField(
            model_name='geoindex',
            name='nearest_landmark',
            field=models.CharField(blank=True, help_text="Pre-computed label like '500m from MG Road'", max_length=200),
        ),
        migrations.AddIndex(
            model_name='geoindex',
            index=models.Index(fields=['geohash6', 'is_active'], name='geo_idx_ghash6_active'),
        ),
        migrations.AddIndex(
            model_name='geoindex',
            index=models.Index(fields=['geohash4'], name='geo_idx_ghash4'),
        ),
    ]
