# Generated by Django 5.1.5 on 2026-03-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_devicefingerprint_fcm_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='holidaycalendar',
            new_name='core_holida_date_2e9cc7_idx',
            old_name='hol_date_country_idx',
        ),
        migrations.RenameIndex(
            model_name='holidaycalendar',
            new_name='core_holida_country_31c8e5_idx',
            old_name='hol_country_state_idx',
        ),
        migrations.RenameIndex(
            model_name='holidaycalendar',
            new_name='core_holida_holiday_0d2248_idx',
            old_name='hol_type_date_idx',
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('search', 'Search'), ('hotel_click', 'Hotel Click'), ('property_view', 'Property View'), ('room_select', 'Room Select'), ('booking_context_created', 'Booking Context Created'), ('booking_attempt', 'Booking Attempt'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('review_submitted', 'Review Submitted'), ('promo_applied', 'Promo Applied'), ('loyalty_redeemed', 'Loyalty Redeemed')], db_index=True, max_length=30),
        ),
    ]
