# Generated by Django 5.1.5 on 2026-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_platformsettings_app_versions_and_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='cashfree_enabled',
            field=models.BooleanField(default=True, help_text='Enable Cashfree PG for bookings'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='max_wallet_topup',
            field=models.DecimalField(decimal_places=2, default=50000, help_text='Maximum wallet top-up (INR)', max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='min_wallet_topup',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Minimum wallet top-up (INR)', max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='offers_enabled',
            field=models.BooleanField(default=True, help_text='Enable offers and coupons system'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paytm_enabled',
            field=models.BooleanField(default=False, help_text='Enable Paytm UPI (pending approval)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='referral_enabled',
            field=models.BooleanField(default=True, help_text='Enable referral program'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_enabled',
            field=models.BooleanField(default=True, help_text='Enable Stripe for international cards'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='wallet_enabled',
            field=models.BooleanField(default=True, help_text='Enable ZygoWallet payment method'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='wallet_topup_enabled',
            field=models.BooleanField(default=True, help_text='Allow wallet top-ups'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='wallet_topup_gateway',
            field=models.CharField(choices=[('cashfree', 'Cashfree'), ('razorpay', 'Razorpay'), ('paytm', 'Paytm')], default='cashfree', help_text='Gateway used for wallet top-up transactions', max_length=20),
        ),
    ]
