# Generated by Django 5.1.5 on 2026-03-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('R', 'Room Only'), ('R+B', 'Room + Breakfast'), ('R+B+L/D', 'Room + Breakfast + Lunch/Dinner'), ('R+A', 'Room + All Meals')], help_text='OTA-standard meal plan code', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Owner-customizable display name', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
