# Generated by Django 5.1.5 on 2026-02-15 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_timer_expires_at'),
        ('promos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promousage',
            options={'verbose_name_plural': 'Promo Usage'},
        ),
        migrations.AddField(
            model_name='promo',
            name='applicable_module',
            field=models.CharField(choices=[('hotels', 'Hotels'), ('buses', 'Buses'), ('cabs', 'Cabs'), ('packages', 'Packages'), ('flights', 'Flights'), ('trains', 'Trains'), ('all', 'All Modules')], default='all', max_length=50),
        ),
        migrations.AddField(
            model_name='promo',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max discount cap', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount')], default='percent', max_length=20),
        ),
        migrations.AlterField(
            model_name='promo',
            name='max_uses',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Discount value (% or amount)', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='promo',
            index=models.Index(fields=['code', 'is_active'], name='promos_prom_code_ccf4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='promo',
            index=models.Index(fields=['applicable_module', 'is_active'], name='promos_prom_applica_89755d_idx'),
        ),
        migrations.AddIndex(
            model_name='promo',
            index=models.Index(fields=['ends_at'], name='promos_prom_ends_at_db2bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='promousage',
            index=models.Index(fields=['promo', 'user'], name='promos_prom_promo_i_0d500b_idx'),
        ),
    ]