# Generated by Django 5.1.5 on 2026-02-28 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_context_and_lifecycle_states'),
        ('hotels', '0017_booking_context_and_lifecycle_states'),
        ('promos', '0002_alter_promousage_options_promo_applicable_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('cashback_type', models.CharField(choices=[('percent', 'Percentage of Booking'), ('flat', 'Flat Amount')], default='percent', max_length=10)),
                ('cashback_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or flat amount in INR.', max_digits=8)),
                ('max_cashback_per_booking', models.DecimalField(decimal_places=2, default=0, help_text='Cap per booking. 0 = no cap.', max_digits=10)),
                ('max_cashback_per_user', models.DecimalField(decimal_places=2, default=0, help_text='Lifetime cap per user. 0 = no cap.', max_digits=10)),
                ('min_booking_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum booking amount to qualify. 0 = no minimum.', max_digits=10)),
                ('cashback_expiry_days', models.PositiveIntegerField(default=365, help_text='Days before credited cashback expires from wallet.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired')], db_index=True, default='active', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('applicable_properties', models.ManyToManyField(blank=True, help_text='Leave empty to apply to all properties.', related_name='cashback_campaigns', to='hotels.property')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cashback Campaign',
                'verbose_name_plural': 'Cashback Campaigns',
            },
        ),
        migrations.CreateModel(
            name='CashbackCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wallet_txn_reference', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_credits', to='booking.booking')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='promos.cashbackcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_credits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
