# Generated by Django 5.1.5 on 2026-03-06 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_booking_check_in_alter_booking_check_out_and_more'),
        ('promos', '0003_cashback_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbackcredit',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashback_credits', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='promousage',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_usages', to='booking.booking'),
        ),
    ]
