# Generated by Django 5.1.5 on 2026-03-06 03:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_bookingcontext_uuid'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('gateway', models.CharField(choices=[('wallet', 'ZygoTrip Wallet'), ('cashfree', 'Cashfree'), ('stripe', 'Stripe'), ('paytm_upi', 'Paytm UPI')], max_length=20)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discrepancy', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transactions_matched', models.IntegerField(default=0)),
                ('transactions_unmatched', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('discrepancy', 'Discrepancy')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'gateway')},
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_id', models.CharField(db_index=True, help_text='Our internal transaction reference', max_length=100, unique=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Client-generated idempotency key', max_length=128, null=True, unique=True)),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, help_text="Gateway's transaction/order ID", max_length=200)),
                ('gateway', models.CharField(choices=[('wallet', 'ZygoTrip Wallet'), ('cashfree', 'Cashfree'), ('stripe', 'Stripe'), ('paytm_upi', 'Paytm UPI')], max_length=20)),
                ('booking_reference', models.CharField(db_index=True, help_text='Booking UUID string', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('webhook_received', models.BooleanField(default=False)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_data', models.JSONField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('refund_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('refund_completed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_gateway_id', models.CharField(blank=True, max_length=200)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='ptxn_user_status_idx'), models.Index(fields=['booking_reference'], name='ptxn_booking_ref_idx'), models.Index(fields=['gateway', 'status'], name='ptxn_gw_status_idx'), models.Index(fields=['gateway_transaction_id'], name='ptxn_gw_txn_idx')],
            },
        ),
    ]
