# Generated by Django 5.1.5 on 2026-03-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_booking_alter_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreconciliation',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
