# Generated by Django 5.1.5 on 2026-03-07 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentreconciliation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('request_path', models.CharField(max_length=255)),
                ('request_hash', models.CharField(blank=True, help_text='SHA256 of request body to detect mismatched replays', max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['idempotency_key', 'status'], name='idempotency_key_status_idx'), models.Index(fields=['expires_at'], name='idempotency_expires_idx')],
            },
        ),
    ]
