# Generated by Django 5.1.5 on 2026-03-07 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_idempotencyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('our_transaction_id', models.CharField(blank=True, db_index=True, help_text='Our PaymentTransaction.transaction_id', max_length=100)),
                ('gateway_settlement_id', models.CharField(blank=True, db_index=True, help_text='Gateway settlement/payout reference', max_length=200)),
                ('our_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gateway_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('match_status', models.CharField(choices=[('auto', 'Auto-Matched'), ('manual', 'Manual Match'), ('unmatched', 'Unmatched')], default='unmatched', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payments.paymentreconciliation')),
            ],
            options={
                'indexes': [models.Index(fields=['reconciliation', 'match_status'], name='payments_re_reconci_e21029_idx')],
            },
        ),
    ]
