# Generated by Django 5.1.5 on 2026-03-18

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_allow_null_user_for_guest_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_order_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Gateway order identifier from webhook payload',
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_payment_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Gateway payment identifier from webhook payload',
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(
                condition=Q(provider_order_id__isnull=False) & ~Q(provider_order_id=''),
                fields=('provider_order_id',),
                name='uniq_ptxn_provider_order_id_not_blank',
            ),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(
                condition=Q(provider_payment_id__isnull=False) & ~Q(provider_payment_id=''),
                fields=('provider_payment_id',),
                name='uniq_ptxn_provider_payment_id_not_blank',
            ),
        ),
    ]
