# Generated by Django 5.1.15 on 2026-02-21 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0009_amenityfilter_cancellationpolicyoption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('available_rooms', models.PositiveIntegerField(default=0)),
                ('last_supplier_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('version', models.IntegerField(default=0)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hotels.property')),
            ],
            options={
                'verbose_name_plural': 'Property Inventories',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price before multipliers', max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Final calculated price', max_digits=10)),
                ('demand_score', models.PositiveSmallIntegerField(default=50, help_text='0-100 demand indicator')),
                ('competitor_price', models.DecimalField(blank=True, decimal_places=2, help_text='Competitor reference price', max_digits=10, null=True)),
                ('price_change_percent', models.FloatField(default=0.0, help_text='% change from previous price')),
                ('calculated_by', models.CharField(default='system', help_text='Which engine calculated this', max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='hotels.property')),
            ],
            options={
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', '-created_at'], name='inventory_p_propert_0fa9ff_idx'), models.Index(fields=['created_at'], name='inventory_p_created_075122_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierPropertyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier_name', models.CharField(choices=[('booking', 'Booking.com'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('oyo', 'OYO'), ('tripadvisor', 'TripAdvisor')], db_index=True, max_length=50)),
                ('external_id', models.CharField(db_index=True, help_text="Supplier's internal ID for this property", max_length=100)),
                ('supplier_property_name', models.CharField(max_length=255)),
                ('supplier_city', models.CharField(max_length=80)),
                ('supplier_lat', models.FloatField(blank=True, help_text='Latitude from supplier data', null=True)),
                ('supplier_lng', models.FloatField(blank=True, help_text='Longitude from supplier data', null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0-1.0 matching confidence score')),
                ('verified', models.BooleanField(default=False, help_text='Manual verification flag (immutable after True)')),
                ('manual_override', models.BooleanField(default=False, help_text='True when mapping was manually overridden')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_maps', to='hotels.property')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_supplier_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified', '-confidence_score'],
                'indexes': [models.Index(fields=['supplier_name', 'external_id'], name='inventory_s_supplie_f2b9dd_idx'), models.Index(fields=['property', 'verified'], name='inventory_s_propert_7ebbe3_idx')],
                'unique_together': {('supplier_name', 'external_id')},
            },
        ),
    ]