# Generated by Django 5.1.5 on 2026-03-06 08:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_booking_check_in_alter_booking_check_out_and_more'),
        ('inventory', '0001_initial'),
        ('rooms', '0009_alter_roominventory_room_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(help_text='Inclusive end date')),
                ('field_changed', models.CharField(help_text='Which field was changed: total_rooms, blocked_rooms, is_closed, rate_override, etc.', max_length=30)),
                ('old_value', models.CharField(blank=True, max_length=50)),
                ('new_value', models.CharField(max_length=50)),
                ('reason', models.CharField(choices=[('initial_setup', 'Initial Setup'), ('owner_update', 'Owner Update'), ('maintenance', 'Maintenance Block'), ('admin_override', 'Admin Override'), ('supplier_sync', 'Supplier Sync'), ('correction', 'Data Correction')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room_type', '-created_at'], name='inventory_i_room_ty_50888a_idx'), models.Index(fields=['reason'], name='inventory_i_reason_58ba9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('total_rooms', models.PositiveIntegerField(default=0, help_text='Total physical rooms of this type')),
                ('available_rooms', models.PositiveIntegerField(default=0, help_text='Rooms available for booking (computed: total - booked - blocked - held)', validators=[django.core.validators.MinValueValidator(0)])),
                ('booked_rooms', models.PositiveIntegerField(default=0, help_text='Rooms with confirmed bookings')),
                ('blocked_rooms', models.PositiveIntegerField(default=0, help_text='Rooms blocked by owner (maintenance, VIP, etc.)')),
                ('held_rooms', models.PositiveIntegerField(default=0, help_text='Rooms in active hold (TTL-limited)')),
                ('rate_override', models.DecimalField(blank=True, decimal_places=2, help_text='Date-specific rate; NULL = use RoomType.base_price', max_digits=10, null=True)),
                ('is_closed', models.BooleanField(db_index=True, default=False, help_text='Close this date for all bookings')),
                ('min_stay', models.PositiveIntegerField(default=1, help_text='Minimum length of stay starting this date')),
                ('max_stay', models.PositiveIntegerField(default=30, help_text='Maximum length of stay starting this date')),
                ('close_to_arrival', models.BooleanField(default=False, help_text='CTA — no new check-ins on this date')),
                ('close_to_departure', models.BooleanField(default=False, help_text='CTD — no check-outs on this date')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_calendar', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['room_type', 'date'],
                'indexes': [models.Index(fields=['room_type', 'date'], name='inventory_i_room_ty_17ac89_idx'), models.Index(fields=['date', 'is_closed'], name='inventory_i_date_6e5cba_idx'), models.Index(fields=['room_type', 'date', 'is_closed'], name='inventory_i_room_ty_b0a8f2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('available_rooms__gte', 0)), name='invcal_available_non_negative'), models.CheckConstraint(condition=models.Q(('min_stay__gte', 1)), name='invcal_min_stay_positive')],
                'unique_together': {('room_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='InventoryHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hold_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('rooms_held', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted to Booking'), ('expired', 'Expired'), ('released', 'Manually Released')], db_index=True, default='active', max_length=20)),
                ('hold_expires_at', models.DateTimeField(db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_holds', to='booking.booking')),
                ('booking_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_holds', to='booking.bookingcontext')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_holds', to='rooms.roomtype')),
            ],
            options={
                'indexes': [models.Index(fields=['room_type', 'date', 'status'], name='inventory_i_room_ty_06513b_idx'), models.Index(fields=['status', 'hold_expires_at'], name='inventory_i_status_cfeb96_idx'), models.Index(fields=['booking_context'], name='inventory_i_booking_6103df_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('event', models.CharField(choices=[('hold_created', 'Hold Created'), ('hold_released', 'Hold Released'), ('hold_expired', 'Hold Expired'), ('hold_converted', 'Hold Converted'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('adjustment', 'Manual Adjustment'), ('supplier_sync', 'Supplier Sync')], db_index=True, max_length=30)),
                ('quantity', models.IntegerField(help_text='Rooms affected (positive or negative)')),
                ('available_before', models.PositiveIntegerField()),
                ('available_after', models.PositiveIntegerField()),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='Booking UUID, hold UUID, or adjustment UUID', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_log_entries', to=settings.AUTH_USER_MODEL)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_logs', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room_type', 'date', '-created_at'], name='inventory_i_room_ty_34a298_idx'), models.Index(fields=['event', '-created_at'], name='inventory_i_event_00c210_idx'), models.Index(fields=['reference_id'], name='inventory_i_referen_f3e830_idx')],
            },
        ),
    ]
