# Generated by Django 5.1.5 on 2026-03-07 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryadjustment_inventorycalendar_inventoryhold_and_more'),
        ('rooms', '0009_alter_roominventory_room_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_room_id', models.CharField(db_index=True, max_length=100)),
                ('supplier_room_name', models.CharField(max_length=255)),
                ('canonical_name', models.CharField(blank=True, help_text='Normalized room name (e.g. Deluxe, Standard)', max_length=100)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('bed_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('match_confidence', models.FloatField(default=0.0, help_text='0.0-1.0 room matching confidence')),
                ('room_type', models.ForeignKey(blank=True, help_text='Matched internal room type (null if unmatched)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_rooms', to='rooms.roomtype')),
                ('supplier_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_rooms', to='inventory.supplierpropertymap')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierRatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_rate_plan_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('plan_type', models.CharField(choices=[('standard', 'Standard'), ('non_refundable', 'Non-Refundable'), ('member', 'Member Rate'), ('pay_at_hotel', 'Pay at Hotel'), ('free_cancel', 'Free Cancellation')], default='standard', max_length=30)),
                ('meal_plan_code', models.CharField(blank=True, help_text='Supplier meal plan code (mapped to RoomMealPlan.code)', max_length=30)),
                ('is_refundable', models.BooleanField(default=True)),
                ('cancellation_deadline_hours', models.PositiveIntegerField(default=24, help_text='Hours before check-in for free cancellation')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('supplier_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='inventory.supplierroom')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('available_rooms', models.PositiveIntegerField(default=0)),
                ('rate_per_night', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_stay', models.PositiveIntegerField(default=1)),
                ('max_stay', models.PositiveIntegerField(default=30)),
                ('is_closed', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('rate_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='inventory.supplierrateplan')),
                ('supplier_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='inventory.supplierroom')),
            ],
        ),
        migrations.AddIndex(
            model_name='supplierroom',
            index=models.Index(fields=['room_type', 'is_active'], name='inventory_s_room_ty_0c4171_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierroom',
            unique_together={('supplier_map', 'external_room_id')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierrateplan',
            unique_together={('supplier_room', 'external_rate_plan_id')},
        ),
        migrations.AddIndex(
            model_name='supplierinventory',
            index=models.Index(fields=['date', 'is_closed'], name='inventory_s_date_5e263b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinventory',
            index=models.Index(fields=['supplier_room', 'date'], name='inventory_s_supplie_b5766d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierinventory',
            unique_together={('supplier_room', 'rate_plan', 'date')},
        ),
    ]
