# Generated by Django 5.1.5 on 2026-03-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_room_rateplan_inventory'),
        ('rooms', '0009_alter_roominventory_room_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier_name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('timeout_requests', models.PositiveIntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(default=0)),
                ('p99_latency_ms', models.FloatField(default=0)),
                ('error_rate', models.FloatField(default=0, help_text='0-1 ratio')),
                ('is_healthy', models.BooleanField(db_index=True, default=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_reason', models.CharField(blank=True, max_length=200)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inventoryhold',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('payment_pending', 'Payment in Progress'), ('converted', 'Converted to Booking'), ('expired', 'Expired'), ('released', 'Manually Released'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('direct_available', models.PositiveIntegerField(default=0)),
                ('direct_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier_available', models.PositiveIntegerField(default=0)),
                ('best_supplier_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('best_supplier_name', models.CharField(blank=True, max_length=50)),
                ('total_available', models.PositiveIntegerField(default=0)),
                ('best_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_closed', models.BooleanField(default=False)),
                ('last_recomputed', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_pool', to='rooms.roomtype')),
            ],
            options={
                'indexes': [models.Index(fields=['room_type', 'date', 'is_closed'], name='inventory_i_room_ty_f48947_idx'), models.Index(fields=['date', 'total_available'], name='inventory_i_date_f0bee8_idx')],
                'unique_together': {('room_type', 'date')},
            },
        ),
    ]
