# Generated by Django 5.1.5 on 2026-03-07 08:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0025_reviewfraudflag'),
        ('inventory', '0004_supplierhealth_alter_inventoryhold_status_and_more'),
        ('rooms', '0009_alter_roominventory_room_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('booking_com', 'Booking.com'), ('expedia', 'Expedia'), ('agoda', 'Agoda'), ('goibibo', 'Goibibo'), ('makemytrip', 'MakeMyTrip'), ('airbnb', 'Airbnb')], max_length=30)),
                ('external_property_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='active', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sync_rates', models.BooleanField(default=True)),
                ('sync_availability', models.BooleanField(default=True)),
                ('rate_markup_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Markup percentage applied to rates pushed to this channel', max_digits=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_connections', to='hotels.property')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAvailabilitySync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('availability_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_syncs', to='inventory.channelconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelRateSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[('push', 'Push (ZygoTrip → Channel)'), ('pull', 'Pull (Channel → ZygoTrip)')], max_length=10)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('rates_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_syncs', to='inventory.channelconnection')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='inventory.channelconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='channelconnection',
            index=models.Index(fields=['channel', 'status'], name='chan_channel_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelconnection',
            unique_together={('property', 'channel')},
        ),
        migrations.AddIndex(
            model_name='channelwebhooklog',
            index=models.Index(fields=['channel', 'event_type', '-created_at'], name='chan_webhook_type_idx'),
        ),
    ]
