# Generated by Django 5.1.5 on 2026-03-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_channelconnection_channelavailabilitysync_and_more'),
        ('rooms', '0009_alter_roominventory_room_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorycalendar',
            index=models.Index(fields=['room_type', 'date', 'available_rooms'], name='invcal_avail_range_idx'),
        ),
    ]
