# Generated by Django 5.1.5 on 2026-02-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='timer_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]