# Generated by Django 5.1.5 on 2026-02-15 12:24

from apps.core import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_timer_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(validators=[validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(validators=[validators.validate_future_date]),
        ),
    ]