# Generated by Django 5.1.5 on 2026-02-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_check_in_alter_booking_check_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRetryQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.PositiveIntegerField(db_index=True)),
                ('booking_data', models.JSONField()),
                ('resource_type', models.CharField(max_length=20)),
                ('resource_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('last_error', models.TextField(blank=True)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['next_retry_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='booking_boo_status_a8322a_idx'), models.Index(fields=['user_id', 'status'], name='booking_boo_user_id_0708dd_idx')],
            },
        ),
    ]