# Generated by Django 5.2.11 on 2026-02-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_guest_email_booking_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('hold', 'Hold'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('settlement_pending', 'Settlement Pending'), ('pending', 'Pending'), ('review', 'Review'), ('payment', 'Payment')], db_index=True, default='hold', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='status',
            field=models.CharField(choices=[('hold', 'Hold'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('settlement_pending', 'Settlement Pending'), ('pending', 'Pending'), ('review', 'Review'), ('payment', 'Payment')], max_length=20),
        ),
    ]
