# Generated by Django 5.2.11 on 2026-02-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_hold_expires_at_alter_booking_status_and_more'),
        ('hotels', '0011_add_property_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform commission (Zygotrip cut)', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='gateway_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Payment gateway fee', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total booking value before commission', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='18% GST on gross amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='net_payable_to_hotel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='gross_amount - commission_amount - gateway_fee', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_reference_id',
            field=models.CharField(blank=True, db_index=True, help_text='Payment gateway transaction ID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount refunded to customer (if cancelled)', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_reference_id',
            field=models.CharField(blank=True, db_index=True, help_text='Payment gateway refund ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='settlement_status',
            field=models.CharField(choices=[('unsettled', 'Unsettled'), ('settlement_pending', 'Settlement Pending'), ('settled', 'Settled')], db_index=True, default='unsettled', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('hold', 'Hold'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('settlement_pending', 'Settlement Pending'), ('pending', 'Pending'), ('review', 'Review'), ('payment', 'Payment')], db_index=True, default='hold', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='status',
            field=models.CharField(choices=[('hold', 'Hold'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('settlement_pending', 'Settlement Pending'), ('pending', 'Pending'), ('review', 'Review'), ('payment', 'Payment')], max_length=20),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('period_start', models.DateField(db_index=True, help_text='Settlement period start date')),
                ('period_end', models.DateField(db_index=True, help_text='Settlement period end date (inclusive)')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, help_text='Sum of gross_amount from CONFIRMED bookings', max_digits=15)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, help_text='Sum of commission_amount (Zygotrip cuts)', max_digits=15)),
                ('total_gateway_fee', models.DecimalField(decimal_places=2, default=0, help_text='Sum of gateway_fee', max_digits=15)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, help_text='gross - commission - gateway_fee', max_digits=15)),
                ('total_refunded', models.DecimalField(decimal_places=2, default=0, help_text='Total refunds awarded in this period', max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, help_text='When payment was completed', null=True)),
                ('payment_reference_id', models.CharField(blank=True, help_text='Reference ID from payment system', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Settlement notes or issues')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='hotels.property')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='SettlementLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gateway_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_line_items', to='booking.booking')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='booking.settlement')),
            ],
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['hotel', 'status'], name='booking_set_hotel_i_9b140c_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['period_start', 'status'], name='booking_set_period__58b16d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='settlement',
            unique_together={('hotel', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='settlementlineitem',
            index=models.Index(fields=['settlement'], name='booking_set_settlem_a82e18_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementlineitem',
            index=models.Index(fields=['booking'], name='booking_set_booking_48b3b5_idx'),
        ),
    ]
