# Generated by Django 5.1.5 on 2026-02-28 03:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_commission_amount_booking_gateway_fee_and_more'),
        ('hotels', '0017_booking_context_and_lifecycle_states'),
        ('rooms', '0005_add_meal_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('hold', 'Hold'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('settlement_pending', 'Settlement Pending'), ('settled', 'Settled'), ('pending', 'Pending'), ('review', 'Review'), ('payment', 'Payment')], db_index=True, default='hold', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('hold', 'Hold'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('settlement_pending', 'Settlement Pending'), ('settled', 'Settled'), ('pending', 'Pending'), ('review', 'Review'), ('payment', 'Payment')], max_length=20),
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('policy_type', models.CharField(choices=[('flexible', 'Flexible (Free cancel 48h+)'), ('moderate', 'Moderate (Free cancel 24h+, 50% after)'), ('strict', 'Strict (50% cancel 7d+, non-refundable after)'), ('non_refundable', 'Non-Refundable'), ('custom', 'Custom Policy')], default='flexible', max_length=20)),
                ('free_cancel_hours', models.PositiveIntegerField(default=48, help_text='Hours before check-in within which full refund applies. 0 = no free window.')),
                ('partial_refund_enabled', models.BooleanField(default=True, help_text='If True, a partial refund window applies between tiers 1 and 3.')),
                ('partial_refund_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Percentage of booking value refunded in the partial window.', max_digits=5)),
                ('partial_cancel_hours', models.PositiveIntegerField(default=24, help_text='Hours before check-in at which partial refund applies (must be < free_cancel_hours).')),
                ('non_refundable_hours', models.PositiveIntegerField(default=0, help_text='Cancellations within this many hours of check-in = 0% refund.')),
                ('platform_fee_always_withheld', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Platform convenience fee % always withheld even in free cancellations.', max_digits=5)),
                ('display_note', models.CharField(blank=True, help_text='Human-readable policy summary shown on booking page.', max_length=300)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policy', to='hotels.property')),
            ],
        ),
        migrations.CreateModel(
            name='BookingContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('meal_plan', models.CharField(blank=True, max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('property_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promo_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promo_code', models.CharField(blank=True, max_length=30)),
                ('context_status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted to Booking'), ('expired', 'Expired'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contexts', to='booking.booking')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_contexts', to='hotels.property')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_contexts', to='rooms.roomtype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key'], name='bkctx_session_idx'), models.Index(fields=['user', 'context_status'], name='bkctx_user_status_idx'), models.Index(fields=['expires_at'], name='bkctx_expires_idx')],
            },
        ),
    ]
