# Generated by Django 5.1.5 on 2026-03-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_context_and_lifecycle_states'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingRetryQueue',
        ),
    ]
