# Generated by Django 5.1.5 on 2026-03-06 08:34

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_booking_property_alter_booking_user'),
        ('hotels', '0023_alter_property_owner'),
        ('rooms', '0008_alter_roomimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(db_index=True, validators=[apps.core.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(db_index=True, validators=[apps.core.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='bookingcontext',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_contexts', to='hotels.property'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roomtype'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='hotels.property'),
        ),
        migrations.AlterField(
            model_name='settlementlineitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_line_items', to='booking.booking'),
        ),
    ]
