# Generated by Django 5.1.5 on 2026-03-06 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_booking_bk_status_hold_idx_and_more'),
        ('core', '0017_device_fingerprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_guest_booking',
            field=models.BooleanField(db_index=True, default=False, help_text='True if booked without authentication'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, help_text='NULL for guest bookings (anonymous checkout)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GuestBookingContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('fraud_score', models.IntegerField(default=0, help_text='Fraud score at time of booking (0-100)')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_context', to='booking.booking')),
                ('booking_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_contexts', to='booking.bookingcontext')),
                ('device_fingerprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_bookings', to='core.devicefingerprint')),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='gbc_email_idx'), models.Index(fields=['session_key'], name='gbc_session_idx')],
            },
        ),
    ]
