# Generated by Django 5.1.5 on 2026-03-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_phase17_guest_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcontext',
            name='locked_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The exact price the customer will pay (immutable after lock)', max_digits=12),
        ),
        migrations.AddField(
            model_name='bookingcontext',
            name='meal_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total meal add-on cost (price_modifier × nights × rooms)', max_digits=12),
        ),
        migrations.AddField(
            model_name='bookingcontext',
            name='price_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the price lock expires (same as expires_at by default)', null=True),
        ),
        migrations.AddField(
            model_name='bookingcontext',
            name='price_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='True when price snapshot is locked for checkout'),
        ),
        migrations.AddField(
            model_name='bookingcontext',
            name='rate_plan_id',
            field=models.CharField(blank=True, help_text='External rate plan identifier (from supplier)', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingcontext',
            name='supplier_id',
            field=models.CharField(blank=True, help_text='Supplier identifier for this rate', max_length=100),
        ),
    ]
