# Generated by Django 5.1.5 on 2026-03-07 08:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_price_lock_meal_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.CharField(choices=[('force_majeure', 'Force Majeure (natural disaster, pandemic, etc.)'), ('medical', 'Medical Emergency'), ('duplicate', 'Duplicate Booking'), ('property_issue', 'Property Issue (overbooking, closure)'), ('platform_error', 'Platform Error'), ('goodwill', 'Goodwill Gesture')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('evidence_urls', models.JSONField(blank=True, default=list, help_text='List of uploaded evidence URLs')),
                ('override_refund_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Refund percentage to grant if approved', max_digits=5)),
                ('waive_platform_fee', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_exceptions', to='booking.booking')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
