# Generated by Django 5.1.5 on 2026-03-10 10:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_cancellationexception'),
        ('rooms', '0009_alter_roominventory_room_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePlanPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('free_cancel', 'Free Cancellation'), ('partial_refund', 'Partial Refund'), ('non_refundable', 'Non-Refundable')], default='free_cancel', max_length=20)),
                ('price_modifier_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price adjustment vs base rate. Negative = discount (e.g. -15 for non-refundable).', max_digits=5)),
                ('free_cancel_hours', models.PositiveIntegerField(default=24, help_text='Hours before check-in for full refund. 0 for non-refundable plans.')),
                ('partial_refund_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Refund % in partial window.', max_digits=5)),
                ('partial_cancel_hours', models.PositiveIntegerField(default=12, help_text='Hours before check-in for partial refund.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['display_order', 'plan_type'],
            },
        ),
    ]
