# Generated by Django 5.1.5 on 2026-03-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_rateplanpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('voucher_id', models.CharField(db_index=True, editable=False, help_text='Human-readable voucher ID e.g. ZV-20260311-A1B2C3', max_length=20, unique=True)),
                ('voucher_type', models.CharField(choices=[('hotel', 'Hotel Voucher'), ('bus', 'Bus Ticket'), ('cab', 'Cab Confirmation'), ('flight', 'E-Ticket'), ('activity', 'Activity Voucher'), ('package', 'Package Itinerary')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('booking_uuid', models.UUIDField(db_index=True, help_text='UUID of the source booking')),
                ('booking_ref', models.CharField(help_text='Public booking ID or PNR', max_length=50)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('voucher_data', models.JSONField(default=dict, help_text='Structured voucher content: dates, venue, seat info etc.')),
                ('qr_payload', models.CharField(blank=True, max_length=500)),
                ('qr_hash', models.CharField(blank=True, help_text='SHA-256 of qr_payload', max_length=64)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_uuid'], name='voucher_booking_idx'), models.Index(fields=['voucher_type', 'status'], name='voucher_type_status_idx'), models.Index(fields=['guest_email'], name='voucher_guest_email_idx')],
            },
        ),
    ]
