# Generated by Django 5.1.5 on 2026-03-11 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_bookingvoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recon_date', models.DateField(db_index=True)),
                ('vertical', models.CharField(choices=[('hotel', 'Hotel'), ('flight', 'Flight'), ('bus', 'Bus'), ('cab', 'Cab')], max_length=20)),
                ('total_checked', models.IntegerField(default=0)),
                ('matched', models.IntegerField(default=0)),
                ('mismatched', models.IntegerField(default=0)),
                ('not_found', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-recon_date'],
                'unique_together': {('recon_date', 'vertical')},
            },
        ),
        migrations.CreateModel(
            name='SupplierReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('booking_id', models.IntegerField(db_index=True)),
                ('booking_ref', models.CharField(max_length=100)),
                ('supplier_ref', models.CharField(blank=True, max_length=200)),
                ('our_status', models.CharField(max_length=30)),
                ('supplier_status', models.CharField(blank=True, max_length=30)),
                ('our_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('result', models.CharField(choices=[('matched', 'Matched'), ('mismatch', 'Mismatch'), ('not_found', 'Not Found at Supplier'), ('supplier_error', 'Supplier API Error')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.supplierreconciliation')),
            ],
            options={
                'indexes': [models.Index(fields=['reconciliation', 'result'], name='booking_sup_reconci_768efa_idx'), models.Index(fields=['is_resolved', 'result'], name='booking_sup_is_reso_ac4ffd_idx')],
            },
        ),
    ]
