# Generated by Django 5.1.5 on 2026-03-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_bookinginvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginvoice',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='OTA commission = hotel_amount * commission_pct / 100', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='commission_gst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='18% GST on OTA commission (B2B rate)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='OTA commission percentage (e.g. 15.00)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='customer_gstin',
            field=models.CharField(blank=True, help_text='Customer GSTIN for business travel (optional)', max_length=15),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total discount (promo + property + platform)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='final_customer_price',
            field=models.DecimalField(decimal_places=2, help_text='Total amount charged to customer', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST on accommodation (5% or 18% per slab)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST rate applied (0, 5, or 18)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='hotel_amount',
            field=models.DecimalField(decimal_places=2, help_text='Base room + meal charge before any discounts', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='owner_payout_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount to be paid to property owner after commission', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform service fee (5%, capped Rs.500)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookinginvoice',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, help_text='Supplier/hotel invoice number for B2B settlement', max_length=50),
        ),
    ]
