# Generated by Django 5.1.5 on 2026-02-14 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('operator_name', models.CharField(max_length=100)),
                ('from_city', models.CharField(max_length=50)),
                ('to_city', models.CharField(max_length=50)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_seats', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('amenities', models.CharField(blank=True, help_text='Comma-separated amenities', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(choices=[('sleeper', 'Sleeper'), ('semi_sleeper', 'Semi Sleeper'), ('ac', 'AC'), ('non_ac', 'Non-AC'), ('volvo', 'Volvo'), ('seater', 'Seater')], max_length=50, unique=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('capacity', models.PositiveIntegerField(default=40)),
            ],
            options={
                'verbose_name_plural': 'Bus Types',
            },
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('journey_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('payment', 'Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promo_code', models.CharField(blank=True, max_length=30)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='buses.bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusPriceBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promo_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_breakdown', to='buses.busbooking')),
            ],
            options={
                'verbose_name_plural': 'Bus Price Breakdowns',
            },
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seat_number', models.CharField(max_length=10)),
                ('row', models.CharField(max_length=2)),
                ('column', models.PositiveIntegerField()),
                ('is_ladies_seat', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('ladies', 'Ladies Seat'), ('selected', 'Selected')], default='available', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.bus')),
            ],
            options={
                'unique_together': {('bus', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='BusBookingPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('id_proof_type', models.CharField(blank=True, max_length=50)),
                ('id_proof_number', models.CharField(blank=True, max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='buses.busbooking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buses.busseat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buses.bustype'),
        ),
    ]