# Generated by Django 5.1.5 on 2026-02-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_bus_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='journey_date',
            field=models.DateField(blank=True, help_text='Date of the bus journey', null=True),
        ),
    ]