# Generated by Django 5.1.5 on 2026-02-15 12:24

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_bus_journey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='journey_date',
            field=models.DateField(blank=True, help_text='Date of the bus journey', null=True, validators=[apps.core.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='journey_date',
            field=models.DateField(validators=[apps.core.validators.validate_future_date]),
        ),
    ]