# Generated by Django 5.1.5 on 2026-03-06 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_busbooking_idempotency_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='buses.bus'),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
