# Generated by Django 5.1.5 on 2026-03-10 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0007_alter_bus_operator_alter_busbooking_bus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Majestic Bus Stand', max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('time', models.TimeField(help_text='Boarding time at this point')),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='DroppingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Kempegowda ISBT', max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('time', models.TimeField(help_text='Expected arrival time at this point')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='busseat',
            name='lock_session',
            field=models.CharField(blank=True, help_text='Session/booking reference for this lock', max_length=64),
        ),
        migrations.AddField(
            model_name='busseat',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When the seat was locked (for TTL expiry)', null=True),
        ),
        migrations.AddField(
            model_name='busseat',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='User who currently holds the seat lock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_bus_seats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='busseat',
            name='state',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('ladies', 'Ladies Seat'), ('selected', 'Selected'), ('locked', 'Locked (temp hold)')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='busseat',
            index=models.Index(fields=['state', 'locked_at'], name='buses_busse_state_b4c6f6_idx'),
        ),
        migrations.AddField(
            model_name='boardingpoint',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_points', to='buses.bus'),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='boarding_point',
            field=models.ForeignKey(blank=True, help_text='Selected boarding point', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='buses.boardingpoint'),
        ),
        migrations.AddField(
            model_name='droppingpoint',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropping_points', to='buses.bus'),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='dropping_point',
            field=models.ForeignKey(blank=True, help_text='Selected dropping point', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='buses.droppingpoint'),
        ),
        migrations.AddIndex(
            model_name='boardingpoint',
            index=models.Index(fields=['bus', 'is_active'], name='buses_board_bus_id_e5b350_idx'),
        ),
        migrations.AddIndex(
            model_name='droppingpoint',
            index=models.Index(fields=['bus', 'is_active'], name='buses_dropp_bus_id_3f221d_idx'),
        ),
    ]
