# Generated by Django 5.1.5 on 2026-03-19 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='aiusagelog',
            name='ai_usage_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversationsession',
            name='ai_sess_user_idx',
        ),
        migrations.RemoveField(
            model_name='aiusagelog',
            name='cost_usd',
        ),
        migrations.RemoveField(
            model_name='aiusagelog',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='aiusagelog',
            name='session',
        ),
        migrations.RemoveField(
            model_name='aiusagelog',
            name='tokens_used',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='title',
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='model',
            field=models.CharField(default='claude-sonnet-4-6', max_length=100),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
