# Generated by Django 5.1.5 on 2026-02-28 03:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total settled earnings available for withdrawal', max_digits=15)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Earnings from confirmed bookings not yet checked out', max_digits=15)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime total settled to this wallet', max_digits=15)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('bank_account_name', models.CharField(blank=True, max_length=120)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('upi_id', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False, help_text='Bank/UPI details verified by admin before payout')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('txn_type', models.CharField(choices=[('settlement', 'Settlement'), ('pending', 'Pending Settlement'), ('reversal', 'Reversal'), ('withdrawal', 'Bank Withdrawal'), ('adjustment', 'Manual Adjustment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('booking_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('owner_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.ownerwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available balance (spendable immediately)', max_digits=12)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Funds held for in-flight bookings (not spendable)', max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('txn_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('payment', 'Booking Payment'), ('refund', 'Refund'), ('cashback', 'Cashback'), ('settlement', 'Settlement'), ('lock', 'Lock'), ('unlock', 'Unlock'), ('promo', 'Promo Credit')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive=credit, Negative=debit', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Wallet balance snapshot after this transaction', max_digits=12)),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Booking ID, payment transaction ID, or promo code', max_length=100)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('is_reversed', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'txn_type'], name='wtxn_wallet_type_idx'), models.Index(fields=['reference'], name='wtxn_reference_idx')],
            },
        ),
    ]
