# Generated by Django 5.1.5 on 2026-03-06 08:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_alter_ratingaggregate_property_alter_review_booking_and_more'),
        ('wallet', '0002_alter_wallet_user_alter_wallettransaction_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerwallet',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owner_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownerwallettransaction',
            name='owner_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.ownerwallet'),
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_type', models.CharField(blank=True, help_text='Apply to all properties of this type (e.g., Hotel, Homestay). Empty = global.', max_length=80)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Platform commission percentage', max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('property', models.ForeignKey(blank=True, help_text='NULL = global rule for property_type or all', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='hotels.property')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['property', 'is_active'], name='wallet_comm_propert_f4062f_idx'), models.Index(fields=['property_type', 'is_active'], name='wallet_comm_propert_fe60b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='OwnerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('payout_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('upi', 'UPI')], default='bank', max_length=20)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_payouts', to=settings.AUTH_USER_MODEL)),
                ('owner_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='wallet.ownerwallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_wallet', 'status'], name='wallet_owne_owner_w_18522d_idx'), models.Index(fields=['status', '-created_at'], name='wallet_owne_status_8f5e52_idx')],
            },
        ),
    ]
