# Generated by Django 5.1.5 on 2026-03-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_account_journalentry_ledgerentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='txn_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('payment', 'Booking Payment'), ('refund', 'Refund'), ('cashback', 'Cashback'), ('settlement', 'Settlement'), ('lock', 'Lock'), ('unlock', 'Unlock'), ('promo', 'Promo Credit'), ('loyalty_redeem', 'Loyalty Redemption'), ('referral_bonus', 'Referral Bonus'), ('travel_credit', 'Travel Credit')], db_index=True, max_length=20),
        ),
    ]
