# Generated by Django 5.1.5 on 2026-02-21 00:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("capacity", models.IntegerField(default=1)),
                ("price_per_night", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("base_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("max_guests", models.IntegerField(default=1)),
                ("bed_type", models.CharField(blank=True, max_length=50, null=True)),
                ("room_size_sqm", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="RoomInventory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inventory_date", models.DateField(default=datetime.date.today)),
                ("available_count", models.IntegerField(default=0)),
                ("booked_count", models.IntegerField(default=0)),
                (
                    "room_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rooms.roomtype"),
                ),
            ],
            options={
                "unique_together": {("room_type", "inventory_date")},
            },
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(blank=True, null=True, upload_to="rooms/")),
                ("image_url", models.URLField(blank=True, null=True)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "room_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="rooms.roomtype"),
                ),
            ],
        ),
    ]
