# Generated by Django 5.1.15 on 2026-02-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_remove_propertyamenityfilter_amenity_and_more'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='available_count',
            field=models.IntegerField(default=10, help_text='Available rooms of this type'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='max_occupancy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.property'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_size',
            field=models.IntegerField(default=250, help_text='Room size in sq ft'),
        ),
    ]
