# Generated by Django 5.2.11 on 2026-02-24 11:35

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomtype_available_count_roomtype_max_occupancy_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roominventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='available_rooms',
            field=models.IntegerField(default=0, help_text='Rooms available for booking', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, help_text='Inventory date'),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False, help_text='Is date closed for bookings (e.g., maintenance)'),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per room per night for this date', max_digits=10),
        ),
        migrations.AlterField(
            model_name='roominventory',
            name='inventory_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roominventory',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='rooms.roomtype'),
        ),
        migrations.AlterUniqueTogether(
            name='roominventory',
            unique_together={('room_type', 'date')},
        ),
        migrations.AddIndex(
            model_name='roominventory',
            index=models.Index(fields=['room_type', 'date'], name='rooms_roomi_room_ty_b45c67_idx'),
        ),
        migrations.AddIndex(
            model_name='roominventory',
            index=models.Index(fields=['room_type', 'date', 'is_closed'], name='rooms_roomi_room_ty_fd6fee_idx'),
        ),
        migrations.AddIndex(
            model_name='roominventory',
            index=models.Index(fields=['date', 'is_closed'], name='rooms_roomi_date_b1dde1_idx'),
        ),
        migrations.AddConstraint(
            model_name='roominventory',
            constraint=models.CheckConstraint(condition=models.Q(('available_rooms__gte', 0)), name='roominventory_available_rooms_non_negative'),
        ),
    ]
