# Generated by Django 5.2.11 on 2026-02-25 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roominventory_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='rooms.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Room Amenities',
                'unique_together': {('room_type', 'name')},
            },
        ),
    ]
