# Generated by Django 5.1.5 on 2026-03-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_add_roommealplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomimage',
            options={'ordering': ['display_order', 'id']},
        ),
    ]
