# Generated by Django 5.1.5 on 2026-03-06 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_alter_ratingaggregate_property_alter_review_booking_and_more'),
        ('rooms', '0008_alter_roomimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominventory',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='rooms.roomtype'),
        ),
        migrations.AlterField(
            model_name='roommealplan',
            name='code',
            field=models.CharField(choices=[('R', 'Room Only'), ('R+B', 'Room + Breakfast'), ('R+B+L/D', 'Room + Breakfast + Lunch/Dinner'), ('R+A', 'Room + All Meals')], default='R', max_length=30),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='meal_plan',
            field=models.CharField(choices=[('R', 'Room Only'), ('R+B', 'Room + Breakfast'), ('R+B+L/D', 'Room + Breakfast + Lunch/Dinner'), ('R+A', 'Room + All Meals')], default='R', help_text='Default meal plan code (OTA standard)', max_length=50),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_types', to='hotels.property'),
        ),
    ]
