# Generated by Django 5.1.5 on 2026-03-11 09:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or CSS class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Activity Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('highlights', models.JSONField(blank=True, default=list, help_text='List of highlight strings')),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('exclusions', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of activity in minutes')),
                ('max_participants', models.PositiveIntegerField(default=20)),
                ('min_participants', models.PositiveIntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('extreme', 'Extreme')], default='easy', max_length=15)),
                ('min_age', models.PositiveIntegerField(default=0)),
                ('languages', models.JSONField(blank=True, default=list, help_text='["English", "Hindi"]')),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('child_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('group_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Discount % for groups >= min_group_size', max_digits=5)),
                ('min_group_size', models.PositiveIntegerField(default=5)),
                ('is_instant_confirmation', models.BooleanField(default=True)),
                ('is_free_cancellation', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('supplier_code', models.CharField(blank=True, db_index=True, help_text='External supplier ref', max_length=100)),
                ('supplier', models.ForeignKey(help_text='Activity operator / supplier', on_delete=django.db.models.deletion.PROTECT, related_name='supplied_activities', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activities.activitycategory')),
            ],
            options={
                'ordering': ['-is_featured', '-avg_rating'],
            },
        ),
        migrations.CreateModel(
            name='ActivityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_ref', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('no_show', 'No Show')], default='initiated', max_length=20)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('promo_code', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('special_requests', models.TextField(blank=True)),
                ('supplier_booking_ref', models.CharField(blank=True, max_length=100)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityBookingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('pax_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activities.activitybooking')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hours_before', models.PositiveIntegerField(help_text='Hours before activity start')),
                ('refund_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='activities.activity')),
            ],
            options={
                'ordering': ['-hours_before'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='activities/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityPriceBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('adult_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('child_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('group_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('promo_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_breakdown', to='activities.activitybooking')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=150)),
                ('comment', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified via completed booking')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='activities.activity')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activitybooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_capacity', models.PositiveIntegerField()),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override adult price for this slot (peak pricing)', max_digits=10, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='activities.activity')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='activitybooking',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='activities.activitytimeslot'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['city', 'is_active'], name='activities__city_88376b_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['category', 'is_active'], name='activities__categor_731fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-avg_rating', '-review_count'], name='activities__avg_rat_3a6f79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activityreview',
            unique_together={('activity', 'user')},
        ),
        migrations.AddIndex(
            model_name='activitytimeslot',
            index=models.Index(fields=['activity', 'date'], name='activities__activit_90a5d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activitytimeslot',
            unique_together={('activity', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='activitybooking',
            index=models.Index(fields=['user', 'status'], name='activities__user_id_6cfed8_idx'),
        ),
        migrations.AddIndex(
            model_name='activitybooking',
            index=models.Index(fields=['activity', 'status'], name='activities__activit_e49c25_idx'),
        ),
    ]
