# Generated by Django 5.1.5 on 2026-03-19 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='devicetoken',
            name='unique_user_token',
        ),
        migrations.RemoveField(
            model_name='devicetoken',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='device_token',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='sent_at',
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_f0e72c_idx'),
        ),
    ]
